//! GENERATED by `scripts/gen-rust-mods.mjs` from `schema/mods.json` — do not edit by hand.
//!
//! A mod is added by writing one file, `schema/mods/<id>.json`, then running
//! `node schema/build.mjs && node scripts/gen-rust-mods.mjs`. Everything below is
//! mechanical: the id enums, one `deny_unknown_fields` settings struct per mod, a Rust
//! enum per `enum`-typed setting, the registry entry struct, and the three per-mod
//! dispatches [`Registry::info`], [`Registry::defaults_object`] and [`check_settings`].
//! The reasoning lives next door in `mods.rs`, which is written by hand.
//!
//! `node scripts/gen-rust-mods.mjs --check` is the CI gate that this file still matches
//! the schema. Editing it by hand is the one way the type surface can drift from the
//! contract again — and because every settings struct is `deny_unknown_fields`, a field
//! that drifts out is a runtime parse failure of the *entire* registry, not a warning.

use std::fmt;

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use crate::keybind::{HexColor, Keybind};
use crate::loadout::Anchor;
use crate::Error;

use super::{ModEntry, ModInfo, Registry};

// ---------------------------------------------------------------------------
// identity
// ---------------------------------------------------------------------------

/// One of the 14 mods VOID ships — the closed `mod_id` enum of `schema/mods.json`.
///
/// Used as the key of `loadout.mods`, as the `id` argument of `void.setModSetting`, and as the
/// id of a HUD item.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ModId {
    /// Frames per second, updated once per tick.
    Fps,
    /// WASD, mouse and spacebar tiles that light up as you press them.
    Keystrokes,
    /// Clicks per second over a sliding window.
    Cps,
    /// Round-trip time to the current server.
    Ping,
    /// Player position and facing direction.
    Coordinates,
    /// Worn armor and held item with remaining durability.
    ArmorStatus,
    /// Active potion effects with amplifier and remaining duration.
    PotionEffects,
    /// The VOID mark, drawn over the game.
    Watermark,
    /// Latches sprint instead of holding the key.
    ToggleSprint,
    /// Raises gamma so caves and shadows are fully lit.
    Fullbright,
    /// Draws entity bounding boxes.
    Hitboxes,
    /// Narrows FOV while the zoom key is held.
    Zoom,
    /// Replaces the vanilla crosshair with a configurable one at the exact screen centre.
    Crosshair,
    /// Which way you are facing, as its own placeable readout.
    Direction,
}

impl ModId {
    /// Every mod id, in registry order.
    pub const ALL: [ModId; 14] = [
        ModId::Fps,
        ModId::Keystrokes,
        ModId::Cps,
        ModId::Ping,
        ModId::Coordinates,
        ModId::ArmorStatus,
        ModId::PotionEffects,
        ModId::Watermark,
        ModId::ToggleSprint,
        ModId::Fullbright,
        ModId::Hitboxes,
        ModId::Zoom,
        ModId::Crosshair,
        ModId::Direction,
    ];

    /// The snake_case id used as a `loadout.mods` key and in `mods.<id>.<key>` paths.
    pub fn as_str(self) -> &'static str {
        match self {
            ModId::Fps => "fps",
            ModId::Keystrokes => "keystrokes",
            ModId::Cps => "cps",
            ModId::Ping => "ping",
            ModId::Coordinates => "coordinates",
            ModId::ArmorStatus => "armor_status",
            ModId::PotionEffects => "potion_effects",
            ModId::Watermark => "watermark",
            ModId::ToggleSprint => "toggle_sprint",
            ModId::Fullbright => "fullbright",
            ModId::Hitboxes => "hitboxes",
            ModId::Zoom => "zoom",
            ModId::Crosshair => "crosshair",
            ModId::Direction => "direction",
        }
    }
}

/// The subset of [`ModId`] whose `kind` is `hud`: the 9 mods that own a draggable HUD item.
///
/// A mod may only appear in `loadout.hud` if it is listed here.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HudModId {
    /// Frames per second, updated once per tick.
    Fps,
    /// WASD, mouse and spacebar tiles that light up as you press them.
    Keystrokes,
    /// Clicks per second over a sliding window.
    Cps,
    /// Round-trip time to the current server.
    Ping,
    /// Player position and facing direction.
    Coordinates,
    /// Worn armor and held item with remaining durability.
    ArmorStatus,
    /// Active potion effects with amplifier and remaining duration.
    PotionEffects,
    /// The VOID mark, drawn over the game.
    Watermark,
    /// Which way you are facing, as its own placeable readout.
    Direction,
}

impl HudModId {
    /// Every HUD mod id, in registry order.
    pub const ALL: [HudModId; 9] = [
        HudModId::Fps,
        HudModId::Keystrokes,
        HudModId::Cps,
        HudModId::Ping,
        HudModId::Coordinates,
        HudModId::ArmorStatus,
        HudModId::PotionEffects,
        HudModId::Watermark,
        HudModId::Direction,
    ];

    /// Widens to the full mod id enum.
    pub fn as_mod_id(self) -> ModId {
        match self {
            HudModId::Fps => ModId::Fps,
            HudModId::Keystrokes => ModId::Keystrokes,
            HudModId::Cps => ModId::Cps,
            HudModId::Ping => ModId::Ping,
            HudModId::Coordinates => ModId::Coordinates,
            HudModId::ArmorStatus => ModId::ArmorStatus,
            HudModId::PotionEffects => ModId::PotionEffects,
            HudModId::Watermark => ModId::Watermark,
            HudModId::Direction => ModId::Direction,
        }
    }

    /// Narrows a mod id, returning `None` for a gameplay mod.
    pub fn from_mod_id(id: ModId) -> Option<Self> {
        HudModId::ALL.into_iter().find(|m| m.as_mod_id() == id)
    }

    /// The snake_case id.
    pub fn as_str(self) -> &'static str {
        self.as_mod_id().as_str()
    }
}

/// The subset of [`ModId`] whose `kind` is `gameplay`: the 5 mods an actuator Mixin reads every
/// frame.
///
/// These are the only ids accepted by `void.setGameplay`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GameplayModId {
    /// Latches sprint instead of holding the key.
    ToggleSprint,
    /// Raises gamma so caves and shadows are fully lit.
    Fullbright,
    /// Draws entity bounding boxes.
    Hitboxes,
    /// Narrows FOV while the zoom key is held.
    Zoom,
    /// Replaces the vanilla crosshair with a configurable one at the exact screen centre.
    Crosshair,
}

impl GameplayModId {
    /// Every gameplay mod id, in registry order.
    pub const ALL: [GameplayModId; 5] = [
        GameplayModId::ToggleSprint,
        GameplayModId::Fullbright,
        GameplayModId::Hitboxes,
        GameplayModId::Zoom,
        GameplayModId::Crosshair,
    ];

    /// Widens to the full mod id enum.
    pub fn as_mod_id(self) -> ModId {
        match self {
            GameplayModId::ToggleSprint => ModId::ToggleSprint,
            GameplayModId::Fullbright => ModId::Fullbright,
            GameplayModId::Hitboxes => ModId::Hitboxes,
            GameplayModId::Zoom => ModId::Zoom,
            GameplayModId::Crosshair => ModId::Crosshair,
        }
    }

    /// Narrows a mod id, returning `None` for a HUD mod.
    pub fn from_mod_id(id: ModId) -> Option<Self> {
        GameplayModId::ALL.into_iter().find(|m| m.as_mod_id() == id)
    }

    /// The snake_case id.
    pub fn as_str(self) -> &'static str {
        self.as_mod_id().as_str()
    }
}

// ---------------------------------------------------------------------------
// the factory HUD layout
// ---------------------------------------------------------------------------

/// Where this mod's widget sits on a HUD nobody has touched — the layout of Figma frame
/// 244:1722, which is what a new loadout is seeded with and what the HUD editor's `Reset
/// layout` restores. Anchor plus `dx`/`dy`, exactly as `loadout.json#/definitions/hud_item`,
/// minus the `id` (it is the entry's own) and the per-item `scale` (a factory layout is always
/// 1). The numbers are in the **overlay's own design-canvas pixels** — `VoidClient.pumpUi` fits
/// the view to a 1300 x 820 canvas — because that is the space the page actually lays out in,
/// and they are on a **38-42 px vertical rhythm**, which is what it takes to stack chips that
/// are taller than that without overlapping. They are therefore NOT the tighter offsets in
/// `crates/void-loadout`'s `defaults.rs` library or in `loadout.json`'s own `examples`, whose
/// 18-20 px rhythm belongs to hand-authored product loadouts rather than to the factory layout.
/// Mods that ship off (`coordinates`, `direction`) are placed too: a placement is where a
/// widget *would* go, not whether it is drawn — the `on` setting decides that. Required on
/// every `kind: hud` mod and forbidden on every `kind: gameplay` mod; the per-mod `<id>_entry`
/// definitions are where that is enforced, so a HUD mod with no placement, or a gameplay mod
/// with one, is a schema error rather than a silent default.
///
/// The values come from the compiled-in registry, not from this file; what is generated here is
/// the type the entry needs in order to parse at all.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HudPlacement {
    /// Screen anchor the offsets are measured from. The anchor names a point on the viewport
    /// *and* the matching point on the widget box, which is why `dx` is negative on right-hand
    /// anchors and `dy` negative on bottom ones.
    pub anchor: Anchor,

    /// Horizontal offset in design-canvas pixels from the anchor. Positive is right.
    pub dx: f64,

    /// Vertical offset in design-canvas pixels from the anchor. Positive is down.
    pub dy: f64,
}

impl Registry {
    /// One HUD mod's factory placement — where its widget starts on a HUD nobody has touched.
    ///
    /// Infallible over [`HudModId`]: the schema `required`s `default_placement` on every `kind:
    /// hud` entry and forbids it on every gameplay one, so the `Option` on [`ModEntry`] can
    /// only be `None` for a mod this method cannot be called with.
    pub fn default_placement(&self, id: HudModId) -> HudPlacement {
        let entry = match id {
            HudModId::Fps => self.mods.fps.default_placement,
            HudModId::Keystrokes => self.mods.keystrokes.default_placement,
            HudModId::Cps => self.mods.cps.default_placement,
            HudModId::Ping => self.mods.ping.default_placement,
            HudModId::Coordinates => self.mods.coordinates.default_placement,
            HudModId::ArmorStatus => self.mods.armor_status.default_placement,
            HudModId::PotionEffects => self.mods.potion_effects.default_placement,
            HudModId::Watermark => self.mods.watermark.default_placement,
            HudModId::Direction => self.mods.direction.default_placement,
        };
        entry.expect("schema/mods.json requires default_placement on every kind: hud entry")
    }
}

// ---------------------------------------------------------------------------
// settings enums
// ---------------------------------------------------------------------------

/// One of the five unpressed-key swatches on the Mod settings frame, named by the design token
/// it resolves to (`--bg-shell`, `--surface-2`, `--surface-3`, `--sky`, `--teal`). A name
/// rather than a hex value so the choice survives a theme change.
///
/// `mods.json#/definitions/key_swatch`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum KeySwatch {
    /// `shell`.
    Shell,
    /// `raised`.
    Raised,
    /// `pill`.
    Pill,
    /// `sky`.
    Sky,
    /// `teal`.
    Teal,
}

/// One of the five pressed-key swatches on the Mod settings frame, named by the design token it
/// resolves to (`--accent`, `--sky`, `--warn`, `--danger`, `--teal`). `accent` is the frame's
/// default and follows the loadout accent.
///
/// `mods.json#/definitions/pressed_swatch`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PressedSwatch {
    /// `accent` is the frame's default and follows the loadout accent.
    Accent,
    /// `sky`.
    Sky,
    /// `warn`.
    Warn,
    /// `fear`.
    Fear,
    /// `teal`.
    Teal,
}

/// Ground drawn behind a HUD item, as a step on the system's own scale rather than a colour.
/// `none` is the vanilla treatment and the default — the readout sits on the game. `subtle` is
/// the card ground at low alpha, which is enough to hold a chip together over a busy texture;
/// `solid` is the opaque card ground, for a player who wants the HUD to read as a panel. A step
/// rather than a hex value because a per-mod background colour is what §1 names as the far side
/// of the line.
///
/// Shared by every `kind: hud` mod — `schema/mods/_shared.json#/hud/background`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HudBackground {
    /// `none` is the vanilla treatment and the default — the readout sits on the game.
    None,
    /// `subtle` is the card ground at low alpha, which is enough to hold a chip together over a
    /// busy texture.
    Subtle,
    /// `solid` is the opaque card ground, for a player who wants the HUD to read as a panel.
    Solid,
}

/// Density of a HUD item — the inset between its content and its edge, as one of three steps.
/// `density` is named in §1 as legitimate customisation, and it is what a player actually means
/// by 'make the HUD smaller' when `scale` has already made the text too small to read.
///
/// Shared by every `kind: hud` mod — `schema/mods/_shared.json#/hud/padding`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HudPadding {
    /// `tight`.
    Tight,
    /// `normal`.
    Normal,
    /// `roomy`.
    Roomy,
}

/// Which mouse buttons to count: left only, right only, or both shown side by side.
///
/// `mods.json#/definitions/cps_settings/properties/mode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CpsMode {
    /// `left`.
    Left,
    /// `right`.
    Right,
    /// `both`.
    Both,
}

/// Whether X, Y and Z are stacked on three lines or printed on one. Defaults to `inline`, which
/// is what the HUD frame draws; `stacked` holds the three numbers against one left edge, which
/// is easier to read while moving.
///
/// `mods.json#/definitions/coordinates_settings/properties/layout`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CoordinatesLayout {
    /// `stacked` holds the three numbers against one left edge, which is easier to read while
    /// moving.
    Stacked,
    /// `inline`.
    Inline,
}

/// Whether armor pieces are laid out left to right or top to bottom.
///
/// `mods.json#/definitions/armor_status_settings/properties/orientation`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ArmorStatusOrientation {
    /// `horizontal`.
    Horizontal,
    /// `vertical`.
    Vertical,
}

/// Which parts of the mark are drawn: `full` is the ring plus the VOID wordmark, `mark` is the
/// ring alone, `word` is the wordmark alone.
///
/// `mods.json#/definitions/watermark_settings/properties/style`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WatermarkStyle {
    /// `full` is the ring plus the VOID wordmark.
    Full,
    /// `mark` is the ring alone.
    Mark,
    /// `word` is the wordmark alone.
    Word,
}

/// `toggle` latches sprint until the key is pressed again; `hold` restores vanilla
/// hold-to-sprint but keeps the status readout.
///
/// `mods.json#/definitions/toggle_sprint_settings/properties/mode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToggleSprintMode {
    /// `toggle` latches sprint until the key is pressed again.
    Toggle,
    /// `hold` restores vanilla hold-to-sprint but keeps the status readout.
    Hold,
}

/// Shape drawn at the screen centre.
///
/// `mods.json#/definitions/crosshair_settings/properties/style`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CrosshairStyle {
    /// `default`.
    Default,
    /// `cross`.
    Cross,
    /// `dot`.
    Dot,
    /// `circle`.
    Circle,
    /// `t_shape`.
    TShape,
    /// `none`.
    None,
}

/// How the facing is written. `letter` is the compass abbreviation the Coordinates mod already
/// prints (`N`, `NE`, `SW`) and is what fits a small chip. `word` spells it out (`North`),
/// which is what a player reading at a glance across a screen actually parses. `axis` prints
/// the Minecraft world axis instead (`+X`, `-Z`) — not a compass reading at all, and the one a
/// player wants while running a nether tunnel or lining up a build, because it is the notation
/// coordinates themselves are in.
///
/// `mods.json#/definitions/direction_settings/properties/style`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DirectionStyle {
    /// `letter` is the compass abbreviation the Coordinates mod already prints (`N`.
    Letter,
    /// `word` spells it out (`North`), which is what a player reading at a glance across a
    /// screen actually parses.
    Word,
    /// `axis` prints the Minecraft world axis instead (`+X`.
    Axis,
}

// ---------------------------------------------------------------------------
// per-mod settings
// ---------------------------------------------------------------------------

// Every struct below is `#[serde(deny_unknown_fields)]`: a loadout must never quietly
// carry a setting no version of VOID understands, and `store.rs` has a test that says so.
// The cost is that the field list here must be exactly the schema's property list, which
// is why it is generated rather than typed.

/// FPS display settings.
///
/// Settings for the FPS display HUD mod. Reads `Minecraft.debugFPS` once per tick.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FpsSettings {
    /// Whether the FPS display is enabled.
    pub on: bool,

    /// Size multiplier of the FPS tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,

    /// Alpha of the FPS tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,

    /// Ground drawn behind the FPS tile, as a step on the system's own scale rather than a
    /// colour. `none` is the vanilla treatment and the default — the readout sits on the game.
    /// `subtle` is the card ground at low alpha, which is enough to hold a chip together over a
    /// busy texture; `solid` is the opaque card ground, for a player who wants the HUD to read
    /// as a panel. A step rather than a hex value because a per-mod background colour is what
    /// §1 names as the far side of the line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<HudBackground>,

    /// Whether a hairline is drawn around the FPS tile, at the system's own `--border-panel`
    /// alpha. Boolean rather than a colour or a width for the same reason as `background`: the
    /// edge either separates the chip from the game or it does not, and the one useful answer
    /// is already a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<bool>,

    /// Density of the FPS tile — the inset between its content and its edge, as one of three
    /// steps. `density` is named in §1 as legitimate customisation, and it is what a player
    /// actually means by 'make the HUD smaller' when `scale` has already made the text too
    /// small to read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub padding: Option<HudPadding>,

    /// Text colour of the FPS readout.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<HexColor>,

    /// Whether to render the trailing "FPS" label after the number.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_label: Option<bool>,

    /// Whether the 1% low is drawn as a trailing aside. It is the figure that says whether a
    /// frame rate is actually smooth, and it is also a third number on the chip a player reads
    /// mid-match — so it is a switch rather than something that appears whenever a low has been
    /// measured.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_low: Option<bool>,
}

/// Keystrokes settings.
///
/// Settings for the Keystrokes HUD mod. Fed by the edge-triggered `keys` bridge event (§6.5),
/// never by polling.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct KeystrokesSettings {
    /// Whether the keystrokes overlay is enabled.
    pub on: bool,

    /// Size multiplier of the key tiles.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,

    /// Alpha of the key tiles when a key is not pressed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,

    /// Ground drawn behind the key tiles, as a step on the system's own scale rather than a
    /// colour. `none` is the vanilla treatment and the default — the readout sits on the game.
    /// `subtle` is the card ground at low alpha, which is enough to hold a chip together over a
    /// busy texture; `solid` is the opaque card ground, for a player who wants the HUD to read
    /// as a panel. A step rather than a hex value because a per-mod background colour is what
    /// §1 names as the far side of the line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<HudBackground>,

    /// Whether a hairline is drawn around the key tiles, at the system's own `--border-panel`
    /// alpha. Boolean rather than a colour or a width for the same reason as `background`: the
    /// edge either separates the chip from the game or it does not, and the one useful answer
    /// is already a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<bool>,

    /// Density of the key tiles — the inset between its content and its edge, as one of three
    /// steps. `density` is named in §1 as legitimate customisation, and it is what a player
    /// actually means by 'make the HUD smaller' when `scale` has already made the text too
    /// small to read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub padding: Option<HudPadding>,

    /// Optional key that toggles the keystrokes overlay on and off in game without opening the
    /// menu. NONE leaves it always visible while the mod is on.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keybind: Option<Keybind>,

    /// Whether to render the LMB and RMB tiles under the WASD block.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_mouse: Option<bool>,

    /// Whether to render the spacebar tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_spacebar: Option<bool>,

    /// Whether to render the sneak (shift) tile beside the space bar. The `keys` event has
    /// always carried `shift` and the widget has always been handed it; this is the switch that
    /// draws it. A sneak key is as much a part of reading a PvP player's inputs as the space
    /// bar, which is why the two sit together.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_sneak: Option<bool>,

    /// Whether to print the current CPS inside the LMB and RMB tiles.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_cps: Option<bool>,

    /// Corner radius of a key tile in unscaled GUI pixels, drawn as the `Corner radius` slider
    /// on the Mod settings frame (Figma 244:834). 0 is a square tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub corner_radius: Option<i64>,

    /// Background of an unpressed key tile, as one of the five named swatches the Mod settings
    /// frame offers. A token name rather than a hex value, so the tile keeps following the
    /// theme when the theme changes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key_color: Option<KeySwatch>,

    /// Fill of a pressed key tile, as one of the five named swatches the Mod settings frame
    /// offers. `accent` follows the loadout accent, which is the frame's default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pressed_color: Option<PressedSwatch>,
}

/// CPS counter settings.
///
/// Settings for the CPS counter HUD mod. Derived entirely in JS from mouse edges on the `keys`
/// event (§3), so no Java sensor exists for it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CpsSettings {
    /// Whether the CPS counter is enabled.
    pub on: bool,

    /// Size multiplier of the CPS tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,

    /// Alpha of the CPS tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,

    /// Ground drawn behind the CPS tile, as a step on the system's own scale rather than a
    /// colour. `none` is the vanilla treatment and the default — the readout sits on the game.
    /// `subtle` is the card ground at low alpha, which is enough to hold a chip together over a
    /// busy texture; `solid` is the opaque card ground, for a player who wants the HUD to read
    /// as a panel. A step rather than a hex value because a per-mod background colour is what
    /// §1 names as the far side of the line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<HudBackground>,

    /// Whether a hairline is drawn around the CPS tile, at the system's own `--border-panel`
    /// alpha. Boolean rather than a colour or a width for the same reason as `background`: the
    /// edge either separates the chip from the game or it does not, and the one useful answer
    /// is already a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<bool>,

    /// Density of the CPS tile — the inset between its content and its edge, as one of three
    /// steps. `density` is named in §1 as legitimate customisation, and it is what a player
    /// actually means by 'make the HUD smaller' when `scale` has already made the text too
    /// small to read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub padding: Option<HudPadding>,

    /// Which mouse buttons to count: left only, right only, or both shown side by side.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<CpsMode>,

    /// Whether to render the trailing "CPS" unit after the figures. Every other readout on the
    /// HUD can drop its unit; this one could not, which left it the widest chip on screen for a
    /// player who already knows what the number is.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_label: Option<bool>,

    /// Length of the sliding window in milliseconds over which clicks are counted before being
    /// scaled to clicks per second.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub window_ms: Option<i64>,

    /// Whether the highest rate seen this session is drawn as a trailing aside. `window_ms`
    /// already averages, so the live figure answers "how fast am I clicking"; this answers "how
    /// fast can I", which is the number worth comparing against and the one the live figure
    /// never sits still long enough to show.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_peak: Option<bool>,
}

/// Ping display settings.
///
/// Settings for the Ping display HUD mod. Reads the player's own
/// `NetworkPlayerInfo.responseTime`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PingSettings {
    /// Whether the ping display is enabled.
    pub on: bool,

    /// Size multiplier of the ping tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,

    /// Alpha of the ping tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,

    /// Ground drawn behind the ping tile, as a step on the system's own scale rather than a
    /// colour. `none` is the vanilla treatment and the default — the readout sits on the game.
    /// `subtle` is the card ground at low alpha, which is enough to hold a chip together over a
    /// busy texture; `solid` is the opaque card ground, for a player who wants the HUD to read
    /// as a panel. A step rather than a hex value because a per-mod background colour is what
    /// §1 names as the far side of the line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<HudBackground>,

    /// Whether a hairline is drawn around the ping tile, at the system's own `--border-panel`
    /// alpha. Boolean rather than a colour or a width for the same reason as `background`: the
    /// edge either separates the chip from the game or it does not, and the one useful answer
    /// is already a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<bool>,

    /// Density of the ping tile — the inset between its content and its edge, as one of three
    /// steps. `density` is named in §1 as legitimate customisation, and it is what a player
    /// actually means by 'make the HUD smaller' when `scale` has already made the text too
    /// small to read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub padding: Option<HudPadding>,

    /// Whether to render the trailing "ms" unit after the number.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_label: Option<bool>,

    /// Ping at or below this many milliseconds renders in the good colour.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub good_ms: Option<i64>,

    /// Ping at or above this many milliseconds renders in the bad colour. Must be greater than
    /// `good_ms`; not enforced by the schema.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bad_ms: Option<i64>,

    /// Whether the shortened server name is drawn after the figure. A player who only ever
    /// plays one server is being told something they already know, on the chip they look at
    /// most often.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_host: Option<bool>,
}

/// Coordinates settings.
///
/// Settings for the Coordinates HUD mod. Reads `EntityPlayerSP` position and yaw once per tick.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoordinatesSettings {
    /// Whether the coordinates display is enabled.
    pub on: bool,

    /// Size multiplier of the coordinates tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,

    /// Alpha of the coordinates tile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,

    /// Ground drawn behind the coordinates tile, as a step on the system's own scale rather
    /// than a colour. `none` is the vanilla treatment and the default — the readout sits on the
    /// game. `subtle` is the card ground at low alpha, which is enough to hold a chip together
    /// over a busy texture; `solid` is the opaque card ground, for a player who wants the HUD
    /// to read as a panel. A step rather than a hex value because a per-mod background colour
    /// is what §1 names as the far side of the line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<HudBackground>,

    /// Whether a hairline is drawn around the coordinates tile, at the system's own
    /// `--border-panel` alpha. Boolean rather than a colour or a width for the same reason as
    /// `background`: the edge either separates the chip from the game or it does not, and the
    /// one useful answer is already a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<bool>,

    /// Density of the coordinates tile — the inset between its content and its edge, as one of
    /// three steps. `density` is named in §1 as legitimate customisation, and it is what a
    /// player actually means by 'make the HUD smaller' when `scale` has already made the text
    /// too small to read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub padding: Option<HudPadding>,

    /// Number of decimal places printed for X, Y and Z. Capped at 2 because that is what the
    /// wire carries: the `tick` sensor rounds the position to 2 dp before publishing it, so a
    /// third place could only ever print a zero. Widening it is a bridge change, not a settings
    /// change, and a costly one — 3 dp makes ten times as many positions distinct, and every
    /// distinct position is a HUD repaint.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decimals: Option<i64>,

    /// Whether to append the cardinal direction derived from yaw.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_direction: Option<bool>,

    /// Whether X, Y and Z are stacked on three lines or printed on one. Defaults to `inline`,
    /// which is what the HUD frame draws; `stacked` holds the three numbers against one left
    /// edge, which is easier to read while moving.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub layout: Option<CoordinatesLayout>,

    /// Ink for the readings — the three axes and the cardinal. Not the separator between them:
    /// quiet-cell §1 gives colour to the live value rather than to the punctuation around it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<HexColor>,
}

/// Armor status settings.
///
/// Settings for the Armor status HUD mod. Reads `InventoryPlayer.armorInventory` durability,
/// pushed only when it changes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArmorStatusSettings {
    /// Whether the armor status display is enabled.
    pub on: bool,

    /// Size multiplier of the armor row.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,

    /// Alpha of the armor row.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,

    /// Ground drawn behind the armor row, as a step on the system's own scale rather than a
    /// colour. `none` is the vanilla treatment and the default — the readout sits on the game.
    /// `subtle` is the card ground at low alpha, which is enough to hold a chip together over a
    /// busy texture; `solid` is the opaque card ground, for a player who wants the HUD to read
    /// as a panel. A step rather than a hex value because a per-mod background colour is what
    /// §1 names as the far side of the line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<HudBackground>,

    /// Whether a hairline is drawn around the armor row, at the system's own `--border-panel`
    /// alpha. Boolean rather than a colour or a width for the same reason as `background`: the
    /// edge either separates the chip from the game or it does not, and the one useful answer
    /// is already a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<bool>,

    /// Density of the armor row — the inset between its content and its edge, as one of three
    /// steps. `density` is named in §1 as legitimate customisation, and it is what a player
    /// actually means by 'make the HUD smaller' when `scale` has already made the text too
    /// small to read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub padding: Option<HudPadding>,

    /// Whether armor pieces are laid out left to right or top to bottom.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub orientation: Option<ArmorStatusOrientation>,

    /// Whether to print remaining durability as a number under each piece.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_durability: Option<bool>,

    /// Whether to include the currently held item as a sixth slot.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_held_item: Option<bool>,

    /// Fraction of maximum durability under which a piece's bar turns amber. A threshold on a
    /// live value, the same species as `ping.good_ms`: the point at which a player wants to be
    /// told their gear is going is a matter of how they play, not a constant. 0 never warns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub warn_below: Option<f64>,
}

/// Potion effects settings.
///
/// Settings for the Potion effects HUD mod. Reads `getActivePotionEffects`, pushed only when
/// the set changes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PotionEffectsSettings {
    /// Whether the potion effects display is enabled.
    pub on: bool,

    /// Size multiplier of the effect list.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,

    /// Alpha of the effect list.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,

    /// Ground drawn behind the effect list, as a step on the system's own scale rather than a
    /// colour. `none` is the vanilla treatment and the default — the readout sits on the game.
    /// `subtle` is the card ground at low alpha, which is enough to hold a chip together over a
    /// busy texture; `solid` is the opaque card ground, for a player who wants the HUD to read
    /// as a panel. A step rather than a hex value because a per-mod background colour is what
    /// §1 names as the far side of the line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<HudBackground>,

    /// Whether a hairline is drawn around the effect list, at the system's own `--border-panel`
    /// alpha. Boolean rather than a colour or a width for the same reason as `background`: the
    /// edge either separates the chip from the game or it does not, and the one useful answer
    /// is already a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<bool>,

    /// Density of the effect list — the inset between its content and its edge, as one of three
    /// steps. `density` is named in §1 as legitimate customisation, and it is what a player
    /// actually means by 'make the HUD smaller' when `scale` has already made the text too
    /// small to read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub padding: Option<HudPadding>,

    /// Whether to print the remaining duration next to each effect.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_duration: Option<bool>,

    /// Whether to print the roman-numeral amplifier next to each effect name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_amplifier: Option<bool>,

    /// Whether to omit ambient effects such as a beacon aura from the list.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hide_ambient: Option<bool>,
}

/// VOID watermark settings.
///
/// Settings for the VOID watermark HUD mod. It reads nothing from the game: the overlay draws
/// the mark itself, which is why its `source` says so rather than naming a 1.8.9 field.
/// Modelled on `fps_settings` and `crosshair_settings`, and deliberately without a `color`:
/// `design/quiet-cell-system.md` §1 reserves colour for a live value or a selected item, and a
/// watermark is neither.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WatermarkSettings {
    /// Whether the watermark is drawn.
    pub on: bool,

    /// Size multiplier of the mark.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,

    /// Alpha of the mark. Lower than the other HUD mods by default, so it sits behind the
    /// readouts the player is actually reading.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,

    /// Ground drawn behind the mark, as a step on the system's own scale rather than a colour.
    /// `none` is the vanilla treatment and the default — the readout sits on the game. `subtle`
    /// is the card ground at low alpha, which is enough to hold a chip together over a busy
    /// texture; `solid` is the opaque card ground, for a player who wants the HUD to read as a
    /// panel. A step rather than a hex value because a per-mod background colour is what §1
    /// names as the far side of the line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<HudBackground>,

    /// Whether a hairline is drawn around the mark, at the system's own `--border-panel` alpha.
    /// Boolean rather than a colour or a width for the same reason as `background`: the edge
    /// either separates the chip from the game or it does not, and the one useful answer is
    /// already a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<bool>,

    /// Density of the mark — the inset between its content and its edge, as one of three steps.
    /// `density` is named in §1 as legitimate customisation, and it is what a player actually
    /// means by 'make the HUD smaller' when `scale` has already made the text too small to
    /// read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub padding: Option<HudPadding>,

    /// Which parts of the mark are drawn: `full` is the ring plus the VOID wordmark, `mark` is
    /// the ring alone, `word` is the wordmark alone.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<WatermarkStyle>,
}

/// Toggle sprint settings.
///
/// Settings for the Toggle sprint gameplay mod. Overrides the sprint `KeyBinding` in
/// `onLivingUpdate`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ToggleSprintSettings {
    /// Whether toggle sprint is enabled.
    pub on: bool,

    /// `toggle` latches sprint until the key is pressed again; `hold` restores vanilla
    /// hold-to-sprint but keeps the status readout.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<ToggleSprintMode>,

    /// Whether the same latching behaviour is applied to sneak.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sneak_too: Option<bool>,

    /// Key that toggles the mod in game, captured through
    /// `void.openKeybindCapture('toggle_sprint')`. Distinct from the sprint key itself, which
    /// is vanilla's and is what `mode` latches: this one turns the latching off, for a fight
    /// where holding the key is what the hands expect.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keybind: Option<Keybind>,
}

/// Fullbright settings.
///
/// Settings for the Fullbright gameplay mod. Overrides `gameSettings.gammaSetting`; client-side
/// only and Watchdog-tolerated (§3), but classified `grey` in §11.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FullbrightSettings {
    /// Whether fullbright is enabled.
    pub on: bool,

    /// Value written to `gammaSetting` while the mod is on. Vanilla's slider tops out at 1; 10
    /// is the conventional fullbright value.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gamma: Option<f64>,

    /// Key that toggles the mod in game, captured through
    /// `void.openKeybindCapture('fullbright')`. The mod that most wants one: brightness is
    /// something you change *because* of what is in front of you, and reaching the menu to
    /// change it means the moment has passed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keybind: Option<Keybind>,
}

/// Hitboxes settings.
///
/// Settings for the Hitboxes gameplay mod. Forces `RenderManager.debugBoundingBox`. Classified
/// `grey` in §11.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HitboxesSettings {
    /// Whether entity hitboxes are drawn.
    pub on: bool,

    /// GL line width used for the bounding box wireframe.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub line_width: Option<f64>,

    /// Colour of the bounding box wireframe.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<HexColor>,

    /// Whether to draw the vanilla eye-direction ray along with the box.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_eye_line: Option<bool>,

    /// Colour of the eye-direction ray, when `show_eye_line` draws it. Its own colour rather
    /// than the box's: the ray answers *where is he looking*, which is a different question
    /// from the box's *where is he*, and one colour for both draws a box with a spike on it
    /// rather than two readings.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub eye_line_color: Option<HexColor>,

    /// Furthest an entity can be, in blocks, and still be drawn. The point of a box in a fight
    /// is the entity you are fighting; every box past that is a wireframe over the scenery. 64
    /// is vanilla's own entity render distance, so the default draws what the game was already
    /// drawing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_distance: Option<f64>,

    /// Key that toggles the mod in game, captured through
    /// `void.openKeybindCapture('hitboxes')`. Boxes are worth having for one fight and not the
    /// next, which is a decision made mid-match rather than in a menu.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keybind: Option<Keybind>,
}

/// Zoom settings.
///
/// Settings for the Zoom gameplay mod. Overrides FOV while `key` is held.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ZoomSettings {
    /// Whether zoom is enabled.
    pub on: bool,

    /// Key held to zoom. Captured through `void.openKeybindCapture('zoom')`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key: Option<Keybind>,

    /// The player's FOV is divided by this factor while zoomed. 4 approximates the familiar
    /// Optifine zoom.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fov_divisor: Option<f64>,

    /// Whether the FOV change is eased over a few frames rather than snapping.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub smooth: Option<bool>,

    /// Whether smooth-camera mouse damping is applied while zoomed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cinematic: Option<bool>,
}

/// Crosshair settings.
///
/// Settings for the Crosshair mod. Uniquely among the 13 it is drawn in GL rather than HTML (§3
/// footnote) because it must sit at the exact pixel centre, but it is configured through the
/// same loadout model as everything else.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CrosshairSettings {
    /// Whether the vanilla crosshair pass is replaced.
    pub on: bool,

    /// Shape drawn at the screen centre.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<CrosshairStyle>,

    /// Half-length in pixels of each crosshair arm, before GUI scale.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,

    /// Stroke thickness in pixels, before GUI scale.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub thickness: Option<i64>,

    /// Empty gap in pixels between the centre point and the start of each arm.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gap: Option<i64>,

    /// Colour of the crosshair.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<HexColor>,

    /// Whether a one-pixel black outline is drawn around the shape for contrast.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outline: Option<bool>,

    /// Whether the gap widens while the attack cooldown is not full and while sprinting.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dynamic: Option<bool>,

    /// Whether a dot of `thickness` square is drawn on the centre point, under whatever `style`
    /// draws around it. `dot` is a style, so without this a player must choose between a cross
    /// and a centre reference; every crosshair configurator worth the name lets them have both.
    /// Ignored by `none`, and by `default`, which is the vanilla pass.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub center_dot: Option<bool>,
}

/// Direction settings.
///
/// Settings for the Direction HUD mod. Reads the same `pos.yaw` the tick sensor already sends
/// for Coordinates, so it needs no sensor of its own — which is the whole reason it is cheap to
/// ship. `coordinates.show_direction` is deliberately kept: that is the inline form, a suffix
/// on the coordinate rows, and this is the standalone one a player places on its own and reads
/// at a glance. Both are wanted, they are not duplicates of each other, and neither reads the
/// other's settings.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DirectionSettings {
    /// Whether the direction display is enabled.
    pub on: bool,

    /// Size multiplier of the direction chip.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scale: Option<f64>,

    /// Alpha of the direction chip.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opacity: Option<f64>,

    /// Ground drawn behind the direction chip, as a step on the system's own scale rather than
    /// a colour. `none` is the vanilla treatment and the default — the readout sits on the
    /// game. `subtle` is the card ground at low alpha, which is enough to hold a chip together
    /// over a busy texture; `solid` is the opaque card ground, for a player who wants the HUD
    /// to read as a panel. A step rather than a hex value because a per-mod background colour
    /// is what §1 names as the far side of the line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<HudBackground>,

    /// Whether a hairline is drawn around the direction chip, at the system's own
    /// `--border-panel` alpha. Boolean rather than a colour or a width for the same reason as
    /// `background`: the edge either separates the chip from the game or it does not, and the
    /// one useful answer is already a token.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub border: Option<bool>,

    /// Density of the direction chip — the inset between its content and its edge, as one of
    /// three steps. `density` is named in §1 as legitimate customisation, and it is what a
    /// player actually means by 'make the HUD smaller' when `scale` has already made the text
    /// too small to read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub padding: Option<HudPadding>,

    /// How the facing is written. `letter` is the compass abbreviation the Coordinates mod
    /// already prints (`N`, `NE`, `SW`) and is what fits a small chip. `word` spells it out
    /// (`North`), which is what a player reading at a glance across a screen actually parses.
    /// `axis` prints the Minecraft world axis instead (`+X`, `-Z`) — not a compass reading at
    /// all, and the one a player wants while running a nether tunnel or lining up a build,
    /// because it is the notation coordinates themselves are in.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<DirectionStyle>,

    /// Whether the raw yaw angle is printed after the facing. Off by default: it is a second
    /// number on a chip whose whole job is to be read without reading, and it is only wanted by
    /// players aligning something precisely.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub show_degrees: Option<bool>,

    /// Ink for the facing. Not the degrees aside, when `show_degrees` draws it: that is the
    /// same reading in another unit, and colouring both leaves the chip one solid block with no
    /// hierarchy in it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<HexColor>,
}

// ---------------------------------------------------------------------------
// the registry entries, and the three per-mod dispatches
// ---------------------------------------------------------------------------

/// Every mod VOID ships, keyed by id. Closed set of 14.
///
/// `deny_unknown_fields` here is what makes a mod added to `mods.json` but not to this file a
/// loud failure rather than a silently missing entry.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModRegistryEntries {
    /// FPS display — Frames per second, updated once per tick.
    pub fps: ModEntry<FpsSettings>,

    /// Keystrokes — WASD, mouse and spacebar tiles that light up as you press them.
    pub keystrokes: ModEntry<KeystrokesSettings>,

    /// CPS counter — Clicks per second over a sliding window.
    pub cps: ModEntry<CpsSettings>,

    /// Ping display — Round-trip time to the current server.
    pub ping: ModEntry<PingSettings>,

    /// Coordinates — Player position and facing direction.
    pub coordinates: ModEntry<CoordinatesSettings>,

    /// Armor status — Worn armor and held item with remaining durability.
    pub armor_status: ModEntry<ArmorStatusSettings>,

    /// Potion effects — Active potion effects with amplifier and remaining duration.
    pub potion_effects: ModEntry<PotionEffectsSettings>,

    /// Watermark — The VOID mark, drawn over the game.
    pub watermark: ModEntry<WatermarkSettings>,

    /// Toggle sprint — Latches sprint instead of holding the key.
    pub toggle_sprint: ModEntry<ToggleSprintSettings>,

    /// Fullbright — Raises gamma so caves and shadows are fully lit.
    pub fullbright: ModEntry<FullbrightSettings>,

    /// Hitboxes — Draws entity bounding boxes.
    pub hitboxes: ModEntry<HitboxesSettings>,

    /// Zoom — Narrows FOV while the zoom key is held.
    pub zoom: ModEntry<ZoomSettings>,

    /// Crosshair — Replaces the vanilla crosshair with a configurable one at the exact screen
    /// centre.
    pub crosshair: ModEntry<CrosshairSettings>,

    /// Direction — Which way you are facing, as its own placeable readout.
    pub direction: ModEntry<DirectionSettings>,
}

/// Enabled state plus settings for each mod. Every key is optional: an omitted mod falls back
/// to its registry `defaults`, which is what keeps old loadouts valid as mods are added.
///
/// `deny_unknown_fields` makes a mod the schema has and this struct does not a loud failure at
/// the first `set`, rather than a setting that silently will not store.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[allow(missing_docs)]
pub struct ModStates {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fps: Option<FpsSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub keystrokes: Option<KeystrokesSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cps: Option<CpsSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ping: Option<PingSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub coordinates: Option<CoordinatesSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub armor_status: Option<ArmorStatusSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub potion_effects: Option<PotionEffectsSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub watermark: Option<WatermarkSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub toggle_sprint: Option<ToggleSprintSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fullbright: Option<FullbrightSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hitboxes: Option<HitboxesSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub zoom: Option<ZoomSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub crosshair: Option<CrosshairSettings>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub direction: Option<DirectionSettings>,
}

impl Registry {
    /// Classification and copy for one mod.
    pub fn info(&self, id: ModId) -> ModInfo<'_> {
        match id {
            ModId::Fps => self.mods.fps.info(),
            ModId::Keystrokes => self.mods.keystrokes.info(),
            ModId::Cps => self.mods.cps.info(),
            ModId::Ping => self.mods.ping.info(),
            ModId::Coordinates => self.mods.coordinates.info(),
            ModId::ArmorStatus => self.mods.armor_status.info(),
            ModId::PotionEffects => self.mods.potion_effects.info(),
            ModId::Watermark => self.mods.watermark.info(),
            ModId::ToggleSprint => self.mods.toggle_sprint.info(),
            ModId::Fullbright => self.mods.fullbright.info(),
            ModId::Hitboxes => self.mods.hitboxes.info(),
            ModId::Zoom => self.mods.zoom.info(),
            ModId::Crosshair => self.mods.crosshair.info(),
            ModId::Direction => self.mods.direction.info(),
        }
    }

    /// One mod's factory defaults as a JSON object.
    ///
    /// The dispatch behind [`super::defaults_json`], which is where the reasoning is.
    pub(crate) fn defaults_object(&self, id: ModId) -> Map<String, Value> {
        match id {
            ModId::Fps => self.mods.fps.defaults_object(),
            ModId::Keystrokes => self.mods.keystrokes.defaults_object(),
            ModId::Cps => self.mods.cps.defaults_object(),
            ModId::Ping => self.mods.ping.defaults_object(),
            ModId::Coordinates => self.mods.coordinates.defaults_object(),
            ModId::ArmorStatus => self.mods.armor_status.defaults_object(),
            ModId::PotionEffects => self.mods.potion_effects.defaults_object(),
            ModId::Watermark => self.mods.watermark.defaults_object(),
            ModId::ToggleSprint => self.mods.toggle_sprint.defaults_object(),
            ModId::Fullbright => self.mods.fullbright.defaults_object(),
            ModId::Hitboxes => self.mods.hitboxes.defaults_object(),
            ModId::Zoom => self.mods.zoom.defaults_object(),
            ModId::Crosshair => self.mods.crosshair.defaults_object(),
            ModId::Direction => self.mods.direction.defaults_object(),
        }
    }
}

/// Round-trips a settings object through the type for `id`.
///
/// The dispatch behind [`super::validate_settings`], which is where the reasoning is.
pub(crate) fn check_settings(id: ModId, value: Value) -> Result<Value, Error> {
    match id {
        ModId::Fps => super::check::<FpsSettings>(id, value),
        ModId::Keystrokes => super::check::<KeystrokesSettings>(id, value),
        ModId::Cps => super::check::<CpsSettings>(id, value),
        ModId::Ping => super::check::<PingSettings>(id, value),
        ModId::Coordinates => super::check::<CoordinatesSettings>(id, value),
        ModId::ArmorStatus => super::check::<ArmorStatusSettings>(id, value),
        ModId::PotionEffects => super::check::<PotionEffectsSettings>(id, value),
        ModId::Watermark => super::check::<WatermarkSettings>(id, value),
        ModId::ToggleSprint => super::check::<ToggleSprintSettings>(id, value),
        ModId::Fullbright => super::check::<FullbrightSettings>(id, value),
        ModId::Hitboxes => super::check::<HitboxesSettings>(id, value),
        ModId::Zoom => super::check::<ZoomSettings>(id, value),
        ModId::Crosshair => super::check::<CrosshairSettings>(id, value),
        ModId::Direction => super::check::<DirectionSettings>(id, value),
    }
}

// ---------------------------------------------------------------------------
// Display
// ---------------------------------------------------------------------------

impl fmt::Display for ModId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl fmt::Display for HudModId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl fmt::Display for GameplayModId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
