#!/usr/bin/env node
/**
 * Assemble the shipped CSS and font assets into `dist/`.
 *
 * `tsc` compiles the TypeScript; it does not know about CSS. This step:
 *
 *   1. concatenates `src/styles/*.css` (in filename order) plus `src/noise.css` into a
 *      single `dist/styles.css`, so a consumer makes one import and one request;
 *   2. copies `tokens.css`, `fonts.css`, `tailwind-preset.css` and `tokens.json`;
 *   3. copies `src/fonts/` verbatim, keeping the relative `url()`s in `fonts.css`
 *      valid — the consumer's bundler resolves and fingerprints them from there.
 *
 * There is deliberately no CSS bundler in this package. The stylesheet is plain,
 * dependency-free CSS with `v-`-prefixed class names: it has to survive Ultralight,
 * two different app bundlers and a no-build gallery, and every layer of tooling between
 * the authored rule and the renderer is a layer that can drop a property.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const srcDir = path.join(pkgRoot, 'src');
const distDir = path.join(pkgRoot, 'dist');

mkdirSync(distDir, { recursive: true });

/* ---- 1. styles.css ------------------------------------------------------- */

const stylesDir = path.join(srcDir, 'styles');
const parts = readdirSync(stylesDir)
  .filter((name) => name.endsWith('.css'))
  .sort();

const banner = `/* @void/ui — component styles.
 *
 * GENERATED by scripts/build-css.mjs from src/styles/. Do not edit dist/.
 *
 * Import once in your app entry, after tokens.css and fonts.css:
 *
 *     import '@void/ui/tokens.css';
 *     import '@void/ui/fonts.css';
 *     import '@void/ui/styles.css';
 *
 * Everything is scoped under, or namespaced with, \`v-\`. The reset lives on \`.v-app\`,
 * so put that class on the element that wraps your tree.
 *
 * Sections, in order: ${parts.join(', ')}, noise.css
 */

`;

const css = [
  ...parts.map((name) => {
    const body = readFileSync(path.join(stylesDir, name), 'utf8');
    return `/* === ${name} ${'='.repeat(Math.max(0, 68 - name.length))} */\n\n${body}`;
  }),
  `/* === noise.css ${'='.repeat(58)} */\n\n${readFileSync(path.join(srcDir, 'noise.css'), 'utf8')}`,
].join('\n');

writeFileSync(path.join(distDir, 'styles.css'), banner + css, 'utf8');
process.stdout.write(`built dist/styles.css (${parts.length + 1} sections)\n`);

/* ---- 2. standalone stylesheets and tokens.json --------------------------- */

for (const name of ['tokens.css', 'fonts.css', 'tailwind-preset.css', 'tokens.json']) {
  copyFileSync(path.join(srcDir, name), path.join(distDir, name));
  process.stdout.write(`copied dist/${name}\n`);
}

/* ---- 3. fonts ------------------------------------------------------------ */

const fontsSrc = path.join(srcDir, 'fonts');
const fontsDist = path.join(distDir, 'fonts');
rmSync(fontsDist, { recursive: true, force: true });
mkdirSync(fontsDist, { recursive: true });
let copied = 0;
for (const name of readdirSync(fontsSrc)) {
  copyFileSync(path.join(fontsSrc, name), path.join(fontsDist, name));
  copied += 1;
}
process.stdout.write(`copied dist/fonts/ (${copied} files)\n`);
