#!/usr/bin/env node
/**
 * Build `src/tokens.css`, `src/tokens.json`, `src/tokens.ts` and `src/noise.css`.
 *
 * `pvp/design/` is reference material, read-only for everyone, and nothing imports from
 * it at build time (CONTRACTS.md). So the authored `:root` block is **copied** here
 * verbatim — values are never re-typed and never forked — and everything this package
 * adds goes into clearly separated layers below it:
 *
 *   1. the authored `:root` block, byte-for-byte from `design/tokens.css`;
 *   2. `[data-renderer="ultralight"]` — the fallbacks `design/ultralight-notes.md`
 *      prescribes, and nothing else;
 *   3. `[data-renderer="webview"]` — a no-op marker; the authored values already are
 *      the rich version, so this layer exists only so the attribute is meaningful in
 *      both directions.
 *
 * Run automatically by `pnpm build` and `pnpm typecheck`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { deflateSync } from 'node:zlib';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const designDir = path.resolve(pkgRoot, '../../design');
const srcDir = path.resolve(pkgRoot, 'src');

mkdirSync(srcDir, { recursive: true });

const authored = readFileSync(path.join(designDir, 'tokens.css'), 'utf8');
const authoredJson = readFileSync(path.join(designDir, 'tokens.json'), 'utf8');

/* -------------------------------------------------------------------------- */
/* 1. tokens.css                                                              */
/* -------------------------------------------------------------------------- */

const HEADER = `/* ==========================================================================
   @void/ui — design tokens
   GENERATED by scripts/build-tokens.mjs. Do not edit; edit the generator.

   Layer 1 below is pvp/design/tokens.css, copied verbatim. Layers 2 and 3 are the
   renderer modes: put data-renderer="ultralight" on <html> for the in-game bundle
   and data-renderer="webview" for the launcher. Unset behaves as "webview".

   The in-game renderer is the constraint, not the launcher (CONTRACTS.md), so no
   token below depends on backdrop-filter, mix-blend-mode, text-shadow or a 3D
   transform in a way that breaks when those are dropped: the blur radii are read
   through var(--blur-*), which the ultralight layer sets to 0, and the noise layer
   is only painted under [data-renderer="webview"].
   ========================================================================== */

`;

/**
 * Layer 1b — derived from the authored radii, emitted here rather than in `design/`
 * because nobody edits `design/` (CONTRACTS.md).
 *
 * A component cannot write `backdrop-filter: blur(var(--blur-panel))` and rely on the
 * ultralight layer zeroing the radius, because `blur(0px)` is still a filter function:
 * the element stays a backdrop root, WebKit re-samples everything behind it, and it can
 * no longer scope invalidation to the part that changed. Measured in game, that made a
 * single mod toggle repaint the whole 2771x1532 panel — and sometimes the whole surface —
 * holding the menu to 13-26 repaints/s where the same view sustains 74/s on small damage.
 *
 * So the *whole property value* is the token. Layer 2 sets these to `none`, which is the
 * only value that actually removes the backdrop root.
 */
const DERIVED_LAYER = `

/* ---- Layer 1b: derived from the authored radii (see scripts/build-tokens.mjs) ---- */

:root {
  --backdrop-panel: blur(var(--blur-panel));
  --backdrop-dock: blur(var(--blur-dock));
  --backdrop-dim: blur(var(--blur-dim));
}
`;

/**
 * Layer 2. Every entry traces to a row in design/ultralight-notes.md; the comment
 * names the section it comes from.
 */
const ULTRALIGHT_LAYER = `

/* ==========================================================================
   Layer 2 — [data-renderer="ultralight"]
   The in-game overlay: Ultralight 1.4, a WebKit-derived renderer that is not
   Chromium. Each override below is prescribed by design/ultralight-notes.md.
   ========================================================================== */

[data-renderer='ultralight'] {
  /* §1 backdrop-filter [hard] — the overlay never asks the renderer to blur what is
     behind it. The game blur is a GL pass in the host, composited underneath, so the
     web layer paints a semi-opaque solid instead. 0.97 is the no-GL-blur value; the
     host raises it to the 0.94 variant by setting data-glblur="on" (see below). */
  --panel-bg: rgba(10, 11, 12, 0.97);
  --palette-bg: rgba(10, 11, 12, 0.96);
  --dim-palette: rgba(10, 11, 12, 0.62); /* the authored blur(3px) becomes one flat layer */

  /* Never branch on @supports (backdrop-filter: …) — Ultralight may claim support and
     still no-op. The radii stay zeroed so anything derived from them is inert. */
  --blur-panel: 0px;
  --blur-dock: 0px;
  --blur-dim: 0px;

  /* …but a zero radius does not switch the effect off, and assuming it did cost the
     overlay most of its frame rate. blur(0px) is still a filter function, so the element
     remains a backdrop root: WebKit has to re-sample everything painted behind it and
     cannot scope invalidation to what actually changed. Measured in game — toggling one
     mod damaged 2771x1532 device pixels, the entire panel, and some changes damaged the
     whole 3416x1920 surface. At ~10 ms per damaged megapixel that is a ~12 ms repaint for
     a switch a few hundred pixels wide, which held the menu to 13-26 repaints/s while the
     same view sustains 74/s when the damage is small.
     'none' is the only value that removes the backdrop root, and it costs nothing here:
     the radius was already 0, so the overlay never had a blur to lose — the game blur is
     a GL pass in the host, composited underneath (§1 above). */
  --backdrop-panel: none;
  --backdrop-dock: none;
  --backdrop-dim: none;

  /* §2 mix-blend-mode [hard] — fallback 1, "bake it": skip the runtime noise entirely
     and nudge the base colours ~1% lighter so surfaces do not read as flat black. */
  --surface-1: #1a1d21; /* authored #191c20 */
  --surface-2: #23272c; /* authored #22262b */
  --card-bg: rgba(26, 29, 33, 0.94); /* surface-1 @94%, re-derived from the baked hex */
  --raised-bg: rgba(35, 39, 44, 0.97); /* surface-2 @97% */
  --key-bg: rgba(35, 39, 44, 0.96); /* surface-2 @96% */

  --noise-opacity-frame: 0;
  --noise-opacity-canvas: 0;
  --noise-opacity-card: 0;
  --noise-opacity-raised: 0;
  --noise-opacity-accent: 0;
  --noise-opacity-tint: 0;
  --noise-opacity-chrome: 0;

  /* §8 blurred box-shadow [expensive] — split by area, not by radius.
     A blurred shadow is the costliest primitive a CPU rasteriser has, and it is worse than its
     area suggests because the shadow extends past its element, so a change dirties a rectangle
     larger than the element. Measured in game on a mod toggle: 43-80 ms a repaint with the whole
     authored ramp, 15-25 ms with none of it — more than every other optimisation combined.
     What costs is blur x area, not the radius on its own:
         --shadow-panel   70px over 940x588  ~= 0.79 MP of blur
         --shadow-switch-on 12px over 40x22  ~= 0.005 MP, ~150x cheaper
     So the large surfaces move to the host's GL pass (layer 2b carries their authored values to
     it, and setSurfaces tells it where they are) and everything small stays in CSS, where
     the design keeps its depth for a cost that does not show up in a frame.
     The split is forced as well as economical: the host draws underneath the view, and the panel
     is opaque — a GL shadow for anything *inside* the panel would be hidden behind it. Only
     surfaces that sit over the game can be drawn there. */
  --shadow-panel: none;
  --shadow-dock: none;
  --shadow-toolbar: none;

  /* And the HUD's own, for a second reason: cost is per repaint, and these repaint constantly.
     The keystrokes widget redraws on every key change — measured at 35 repaints a second while
     moving, 10-19 ms each with the keycap shadows on. The menu is the opposite: it repaints when
     you touch it, so a shadow there costs nothing you can feel. The chips sit on the game with
     nothing behind them to cast onto anyway; --inset-key and the border already give them their
     edge. */
  --shadow-key: none;
  --shadow-key-on: none;

  /* Same reasoning inside the menu. What costs is a blur pass on an element that changes while you
     are looking at it, and hover is the worst case — the tile under the cursor repaints every frame
     of a 120 ms transition. --shadow-card-active is a 36px glow on exactly that element, and
     --shadow-tile is on all twelve of them, so their damage unions across the grid. Both go.
     The switch glow and the CTA halo stay: they are what the eye reads as "alive", they sit on
     elements that change once per click rather than per frame, and measured they cost nothing
     that shows. */
  --shadow-tile: none;
  --shadow-card-active: none;

  /* The inset ramp is mostly hard lines, which are free; these three carried a blur and are
     flattened to their hard equivalent. An inset cannot move to GL at all — it is drawn inside an
     opaque element, where the pass underneath never reaches. */
  --inset-canvas: inset 0 -1px 0 0 rgba(255, 255, 255, 0.05), inset 0 1px 0 0 rgba(0, 0, 0, 0.62);
  --inset-accent: inset 0 -1px 0 0 rgba(0, 0, 0, 0.22), inset 0 1.5px 0 0 rgba(255, 255, 255, 0.32);
  --inset-kbd: inset 0 1px 0 0 rgba(0, 0, 0, 0.28);

  /* §7 border-style: dashed on a rounded box [risky] — dash phase on rounded corners is
     inconsistent, so the HUD-editor selection falls back to a solid edge. The
     --accent-tint-faint fill already distinguishes the selection. */
  --selection-border-style: solid;
}

/* §1 host contract: when the GL blur pass is running the host sets data-glblur="on"
   and the panel may sit at the lighter alpha. */
[data-renderer='ultralight'][data-glblur='on'] {
  --panel-bg: rgba(10, 11, 12, 0.94);
}

/* ==========================================================================
   Layer 3 — [data-renderer="webview"]
   The launcher: Electron/Chromium (and the Tauri system webview), which has none of
   the limits above. The authored values in layer 1 already are the rich version, so
   this layer only restates the two tokens layer 2 introduces.
   ========================================================================== */

[data-renderer='webview'] {
  --selection-border-style: dashed;
}

/* Default when <html> carries no data-renderer: behave as the launcher. */
:root {
  --selection-border-style: dashed;
}
`;

/**
 * Layer 2b — the authored shadow values, carried through for the host to draw in GL.
 *
 * Layer 2 sets every `--shadow-*` to `none` because a blurred shadow is the most expensive thing a
 * CPU rasteriser does (see §8 there). Dropping the effect is not the same as dropping the *design*:
 * the host can draw these in GL underneath the view, where a blur costs nothing, and the result is
 * the Figma value rather than an approximation of it.
 *
 * So each authored value is re-emitted as `--shadow-<name>-gl`, read straight out of layer 1 rather
 * than retyped. `design/tokens.css` stays the single source of truth: change the shadow there and
 * both the launcher's CSS and the overlay's GL pass follow, with nothing to keep in sync by hand.
 */
function glShadowLayer(authoredCss) {
  const shadows = [...authoredCss.matchAll(/^\s*(--shadow-[a-z0-9-]+)\s*:\s*([^;]+);/gim)];
  if (shadows.length === 0) return '';
  const lines = shadows.map(([, name, value]) => `  ${name}-gl: ${value.trim()};`);
  return `

/* ==========================================================================
   Layer 2b — [data-renderer="ultralight"], shadows for the GL pass
   The authored values from layer 1, verbatim, for the host to draw beneath the
   view. Layer 2 keeps the CSS properties themselves at \`none\`.
   ========================================================================== */

[data-renderer='ultralight'] {
${lines.join('\n')}
}
`;
}

writeFileSync(
  path.join(srcDir, 'tokens.css'),
  HEADER +
    '/* ---- Layer 1: pvp/design/tokens.css, verbatim ---- */\n\n' +
    authored +
    DERIVED_LAYER +
    ULTRALIGHT_LAYER +
    glShadowLayer(authored),
  'utf8',
);
process.stdout.write('generated src/tokens.css\n');

/* -------------------------------------------------------------------------- */
/* 2. tokens.json + tokens.ts                                                 */
/* -------------------------------------------------------------------------- */

writeFileSync(path.join(srcDir, 'tokens.json'), authoredJson, 'utf8');
process.stdout.write('generated src/tokens.json\n');

// Every custom property declared in the authored :root block, for autocomplete and for
// the gallery's token inspector.
const names = [...authored.matchAll(/^\s*(--[a-z0-9-]+)\s*:/gim)].map((m) => m[1]);
const unique = [...new Set(names)].sort();
writeFileSync(
  path.join(srcDir, 'tokens.ts'),
  `/**
 * GENERATED by scripts/build-tokens.mjs — do not edit.
 *
 * The names of every design token declared in \`tokens.css\`. Values live in CSS, not
 * here: this package ships no runtime CSS-in-JS, so JavaScript only ever needs the
 * name (to read one with \`getComputedStyle\`, or to list them in the gallery).
 */

/** Every design-token custom property name, alphabetically. */
export const TOKEN_NAMES = ${JSON.stringify(unique, null, 2)} as const;

/** One design-token custom property name. */
export type TokenName = (typeof TOKEN_NAMES)[number];

/** The two renderer modes \`data-renderer\` selects between. */
export const RENDERERS = ['ultralight', 'webview'] as const;

/**
 * Which renderer the page is running in.
 *
 * - \`ultralight\` — the in-game overlay, inside the JVM. No backdrop-filter, no
 *   mix-blend-mode, no text-shadow, no 3D transforms, no WebGL, no video.
 * - \`webview\` — the launcher, in Chromium or the system webview. Everything works.
 */
export type Renderer = (typeof RENDERERS)[number];
`,
  'utf8',
);
process.stdout.write('generated src/tokens.ts\n');

/* -------------------------------------------------------------------------- */
/* 3. noise.css — the launcher-only grain layer                               */
/* -------------------------------------------------------------------------- */

/** Minimal PNG encoder: greyscale 8-bit, no filtering. */
function encodePng(width, height, pixels) {
  const crcTable = Array.from({ length: 256 }, (_, n) => {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    return c >>> 0;
  });
  const crc32 = (buffer) => {
    let c = 0xffffffff;
    for (const byte of buffer) c = crcTable[(c ^ byte) & 0xff] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const chunk = (type, data) => {
    const length = Buffer.alloc(4);
    length.writeUInt32BE(data.length);
    const body = Buffer.concat([Buffer.from(type, 'latin1'), data]);
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(crc32(body));
    return Buffer.concat([length, body, crc]);
  };
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 0; // greyscale
  const raw = Buffer.alloc((width + 1) * height);
  for (let y = 0; y < height; y += 1) {
    raw[y * (width + 1)] = 0; // filter: none
    for (let x = 0; x < width; x += 1) raw[y * (width + 1) + 1 + x] = pixels[y * width + x];
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

// A fixed-seed 64×64 grain tile. Deterministic so the committed CSS never churns.
const SIZE = 64;
let seed = 0x9f8bff;
const rand = () => {
  seed = (seed * 1664525 + 1013904223) >>> 0;
  return seed / 4294967296;
};
const pixels = new Uint8Array(SIZE * SIZE);
for (let i = 0; i < pixels.length; i += 1) {
  // Centred on mid-grey: `overlay` leaves mid-grey untouched, so the tile only ever
  // nudges a surface a little lighter or a little darker.
  pixels[i] = Math.max(0, Math.min(255, Math.round(128 + (rand() - 0.5) * 90)));
}
const noiseDataUri = `data:image/png;base64,${encodePng(SIZE, SIZE, pixels).toString('base64')}`;

writeFileSync(
  path.join(srcDir, 'noise.css'),
  `/* GENERATED by scripts/build-tokens.mjs — do not edit.

   The grain the design puts over every surface, as a 64px tile scaled to the authored
   --noise-tile size. Painted **only** under [data-renderer="webview"]: Ultralight does
   not implement separable blend modes on composited layers, and the noise would paint
   as an opaque grey wash or be skipped — both worse than no noise
   (design/ultralight-notes.md §2). The ultralight layer bakes a ~1% lift into the base
   hexes instead. */

:root {
  --noise-image: url('${noiseDataUri}');
}

[data-renderer='webview'] .v-noise::after,
:root:not([data-renderer]) .v-noise::after {
  content: '';
  position: absolute;
  inset: 0;
  border-radius: inherit;
  pointer-events: none;
  background-image: var(--noise-image);
  background-size: var(--noise-tile) var(--noise-tile);
  mix-blend-mode: overlay;
  opacity: var(--v-noise-opacity, var(--noise-opacity-card));
}
`,
  'utf8',
);
process.stdout.write('generated src/noise.css\n');
