#!/usr/bin/env node
/**
 * Build `src/tokens.css`, `src/tokens.json`, `src/tokens.ts` and `src/noise.css`.
 *
 * `pvp/design/` is reference material, read-only for everyone, and nothing imports from
 * it at build time (CONTRACTS.md). So the authored `:root` block is **copied** here
 * verbatim — values are never re-typed and never forked — and everything this package
 * adds goes into clearly separated layers below it:
 *
 *   1. the authored `:root` block, byte-for-byte from `design/tokens.css`;
 *   2. `[data-renderer="ultralight"]` — the fallbacks `design/ultralight-notes.md`
 *      prescribes, and nothing else;
 *   3. `[data-renderer="webview"]` — a no-op marker; the authored values already are
 *      the rich version, so this layer exists only so the attribute is meaningful in
 *      both directions.
 *
 * Run automatically by `pnpm build` and `pnpm typecheck`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { deflateSync } from 'node:zlib';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const designDir = path.resolve(pkgRoot, '../../design');
const srcDir = path.resolve(pkgRoot, 'src');

mkdirSync(srcDir, { recursive: true });

const authored = readFileSync(path.join(designDir, 'tokens.css'), 'utf8');
const authoredJson = readFileSync(path.join(designDir, 'tokens.json'), 'utf8');

/* -------------------------------------------------------------------------- */
/* 1. tokens.css                                                              */
/* -------------------------------------------------------------------------- */

const HEADER = `/* ==========================================================================
   @void/ui — design tokens
   GENERATED by scripts/build-tokens.mjs. Do not edit; edit the generator.

   Layer 1 below is pvp/design/tokens.css, copied verbatim. Layers 2 and 3 are the
   renderer modes: put data-renderer="ultralight" on <html> for the in-game bundle
   and data-renderer="webview" for the launcher. Unset behaves as "webview".

   The in-game renderer is the constraint, not the launcher (CONTRACTS.md), so no
   token below depends on backdrop-filter, mix-blend-mode, text-shadow or a 3D
   transform in a way that breaks when those are dropped: the blur radii are read
   through var(--blur-*), which the ultralight layer sets to 0, and the noise layer
   is only painted under [data-renderer="webview"].
   ========================================================================== */

`;

/**
 * Layer 1a — the quiet cell system (`design/quiet-cell-system.md`).
 *
 * That file is the contract, and where it and the authored `design/tokens.css` disagree
 * it wins. `design/` is read-only reference material, so layer 1 above is still copied
 * verbatim — every token *name* it declares survives, which is what keeps the launcher,
 * the overlay and the gallery compiling — and this layer restates the *values* the
 * contract settles. Nothing is renamed; a name whose meaning the contract dropped is
 * aliased onto the value that replaced it.
 *
 * The three structural changes, in the contract's own order:
 *
 *   §1  Four fill steps carry state — shell -> ground -> card -> raised — so no surface
 *       needs a shadow, a blur or a gradient to read as raised. Every `--shadow-*`,
 *       `--inset-*`, `--blur-*` and scrim below is therefore `none`/`0`, and `--card-bg`
 *       is opaque: a translucent card over a translucent panel was the old way of
 *       implying depth, and the ramp does that job now.
 *   §1  Colour marks the live value or the selected item and nothing else, so the accent
 *       tints become white alphas and the accent *inks* and borders read
 *       `var(--hue, var(--accent))` — a mod sets `--hue` on its root and the whole
 *       component tree follows it to that mod's category hue.
 *   §2  One family, Outfit, at 300/400/500. `--font-display` and `--font-mono` are
 *       aliases; the size ramp collapses onto four tiers and every old `--text-*` name
 *       points at its nearest tier.
 */
const QUIET_CELL_LAYER = `

/* ==========================================================================
   Layer 1a — the quiet cell system
   design/quiet-cell-system.md, which wins wherever it and layer 1 disagree.
   Values only: every name layer 1 declares still exists.
   ========================================================================== */

:root {
  /* ------------------------------------------------------------- §1 colour
     The ramp. Four steps, all opaque; the step *is* the state. */
  --bg-shell: #0B0B0C;            /* window chrome, outermost */
  --bg-base: #131315;             /* recessed canvas inside the shell   (GROUND) */
  --card-bg: #191A1C;             /* tiles, panes, cards                (CARD)   */
  --surface-raised: #212225;      /* hover / selected surface           (RAISED) */

  /* The pre-contract surface names, aliased onto the step they now mean. There is no
     third raised step any more: --surface-3 was the "pill" tint and reads as RAISED. */
  --surface-1: var(--card-bg);
  --surface-2: var(--surface-raised);
  --surface-3: var(--surface-raised);
  --raised-bg: var(--surface-raised);
  --key-bg: var(--surface-raised);
  --panel-bg: var(--card-bg);
  --palette-bg: var(--card-bg);
  --dock-bg: var(--card-bg);
  --field-bg: var(--bg-base);
  --kbd-bg: var(--bg-base);
  --kbd-bg-strong: var(--bg-base);
  --stat-tile-bg: var(--bg-base);
  --party-row-bg: var(--bg-base);

  /* The only surfaces that stay translucent are the ones drawn over live game, where
     the thing behind is the match and not another surface of ours. */
  --hud-chip-bg: rgba(11, 11, 12, 0.72);
  --hud-chip-bg-strong: rgba(11, 11, 12, 0.82);

  --text-primary: #EDEEEF;
  --text-secondary: #9A9DA1;
  --text-muted: #626569;

  --ok: #3DD68C;
  --ok-ink: var(--ok);            /* one green, not a green and a lighter green */

  /* Borders are white at low alpha, never a colour. Four steps, and every older
     border name lands on one of them. */
  --border-panel: rgba(255, 255, 255, 0.10);
  --border-raised: rgba(255, 255, 255, 0.07);
  --border-strong: rgba(255, 255, 255, 0.14);
  --divider: rgba(255, 255, 255, 0.045);
  --rim: var(--divider);
  --hairline: var(--border-raised);
  --border-dock: var(--border-panel);
  --border-eyebrow: var(--border-raised);
  --seam: var(--divider);

  /* ------------------------------------------------------- §1 category hues
     A mod's live value, selection dot and drag handles take its category's hue.
     \`--hue\` is deliberately NOT declared here: a rule reads
     \`var(--hue, var(--accent))\`, so it falls back to the default until a mod's root
     sets \`--hue\`. Declaring it globally would make that fallback unreachable. */
  --hue-hud: #9F8BFF;
  --hue-pvp: #FF9E7A;
  --hue-visual: #7ADFFF;
  --hue-utility: #7AE0B0;

  --accent: var(--hue-hud);       /* the default hue */
  --accent-fg: var(--bg-shell);   /* ink ON a hue fill */
  --accent-ink: var(--hue, var(--accent));   /* hue-coloured *text* */

  /* The accent rule: colour is never decoration, so what used to be an accent *tint*
     is a white alpha now. Only the borders and inks — which mark the selected item —
     still carry the hue. */
  --accent-tint: rgba(255, 255, 255, 0.08);
  --accent-tint-weak: rgba(255, 255, 255, 0.06);
  --accent-tint-icon: rgba(255, 255, 255, 0.08);
  --accent-tint-strong: rgba(255, 255, 255, 0.10);
  --accent-tint-faint: rgba(255, 255, 255, 0.04);
  --accent-border: var(--hue, var(--accent));
  --accent-border-strong: var(--hue, var(--accent));
  --ok-tint: rgba(255, 255, 255, 0.08);

  --warn-ink: var(--warn);

  /* Scrims stay; the two gradients do not — §1 allows no gradient anywhere. */
  --dim-overlay: rgba(11, 11, 12, 0.50);
  --dim-palette: rgba(11, 11, 12, 0.55);
  --dim-hud-editor: rgba(11, 11, 12, 0.38);
  --dim-preview: rgba(11, 11, 12, 0.58);
  --scrim-launcher: none;
  --scrim-vignette: none;

  /* ------------------------------------------------------ §3 the cell atom
     Everything textural is a square with a radius of 30% of its size. */
  --cell-radius: 30%;
  --cell-on: rgba(237, 238, 239, 0.40);      /* filled / on   — .36-.45 */
  --cell-off: rgba(237, 238, 239, 0.08);     /* empty / off   — .06-.10 */
  --cell-live: var(--hue, var(--accent));    /* the live value, drawn at .95 */
  --cell-live-alpha: 0.95;

  /* grid texture — 2px cells on an 8px step at 3%, for recessed surfaces. */
  --grid-cell: 2px;
  --grid-step: 8px;
  --grid-alpha: 0.03;

  /* dither — four rows at 15 / 10 / 6 / 3.5%, bottom edge of a raised surface. */
  --dither-row-1: 0.15;
  --dither-row-2: 0.10;
  --dither-row-3: 0.06;
  --dither-row-4: 0.035;

  /* §5 the ambient field: the same cell texture in the hue, ramping 3% -> 22%. */
  --field-alpha-rest: 0.03;
  --field-alpha-hover: 0.22;

  /* §4 the meter: N discrete cells, 12px on a 17px step. */
  --meter-cell: 12px;
  --meter-step: 17px;

  /* ---------------------------------------------------------------- §2 type
     Outfit only. No display face, no monospace — both names stay as aliases so
     no call site breaks, and \`.v-tnum\` restores the digit alignment the mono
     was carrying. */
  --font-ui: "Outfit", system-ui, -apple-system, "Segoe UI", sans-serif;
  --font-display: var(--font-ui);
  --font-mono: var(--font-ui);

  /* 300 Light, 400 Regular, 500 Medium. Nothing heavier — the three names above
     Medium are aliases so \`font-weight: var(--weight-bold)\` still resolves. */
  --weight-light: 300;
  --weight-regular: 400;
  --weight-medium: 500;
  --weight-semibold: var(--weight-medium);
  --weight-bold: var(--weight-medium);
  --weight-extrabold: var(--weight-medium);

  /* The tiers. Do not invent sizes between them.
     Measured off the canonical Figma frames (file RShlfbx2TfxrdleKPIry8w, page
     "Source of truth — Desktop Client"), which use exactly: 8, 8.5, 9, 9.5, 10,
     12.5, 13, 13.5, 14, 15, 17, 30, 36, 88. The first draft of the contract stopped
     display at 40 and aliased --text-hero onto it, which crushed the Play hero
     from 88 to 40 — less than half — and is why the port read as cramped next to
     the frames. Hero and numeral are their own tiers, not roundings of display. */
  --text-display: 30px;      /* screen titles: "Keystrokes", "Mods" */
  --text-display-md: 34px;
  --text-display-lg: 40px;
  --text-numeral: 36px;      /* stat numerals in a card preview: 142, 6.2, 2.0x */
  --text-hero: 88px;         /* the Play hero, and nothing else */
  --text-title: 15px;        /* pane headings, primary buttons */
  --text-title-lg: 17px;
  --text-body: 13px;         /* rows, labels, descriptions */
  --text-body-lg: 14px;
  --text-label: 9px;         /* eyebrows, categories, meta */
  --text-label-lg: 10px;

  /* Every authored size, snapped to its nearest tier. Names kept so the ~200 call
     sites in this package and the two apps keep resolving. */
  --text-2xs: var(--text-label);        /*  8.5 -> 9  */
  --text-xs: var(--text-label);         /*  9         */
  --text-xs-2: var(--text-label-lg);    /*  9.5 -> 10 */
  --text-sm: var(--text-label-lg);      /* 10         */
  --text-sm-2: var(--text-label-lg);    /* 10.5 -> 10 */
  --text-base: var(--text-label-lg);    /* 11   -> 10 */
  --text-base-2: var(--text-body);      /* 11.5 -> 13 */
  --text-md: var(--text-body);          /* 12   -> 13 */
  --text-md-2: var(--text-body);        /* 12.5 -> 13 */
  --text-lg: var(--text-body);          /* 13         */
  --text-lg-2: var(--text-body-lg);     /* 13.5 -> 14 */
  --text-xl: var(--text-body-lg);       /* 14         */
  --text-xl-2: var(--text-title);       /* 15         */
  --text-2xl: var(--text-title-lg);     /* 16   -> 17 */
  --text-3xl: var(--text-title-lg);     /* 17         */
  --text-4xl: var(--text-title-lg);     /* 19   -> 17 */
  --text-5xl: var(--text-title-lg);     /* 22   -> 17 */
  --text-6xl: var(--text-display);      /* 26   -> 30 */
  /* --text-hero is declared above as a tier of its own (88px), not an alias. */

  --leading-nav: 16px;        /* on 13 */
  --leading-title: 34px;      /* on 30 */
  --leading-subtitle: 22px;   /* on 17 */
  --leading-kbd: 13px;        /* on 10 */
  --leading-hero: 44px;       /* on 40 */

  /* Display tracks -0.02em. Body and title track 0. Labels track .12em. */
  --tracking-display: -0.02em;
  --tracking-label: 0.12em;
  --tracking-hero: var(--tracking-display);
  --tracking-title: var(--tracking-display);
  --tracking-subtitle: 0;
  --tracking-pane: 0;
  --tracking-cta: 0;
  --tracking-name: 0;
  --tracking-name-tight: 0;
  --tracking-member: 0;
  --tracking-nav: 0;
  --tracking-cps: 0;
  --tracking-caps-xl: var(--tracking-label);
  --tracking-caps-kbd: var(--tracking-label);
  --tracking-caps-lg: var(--tracking-label);
  --tracking-caps: var(--tracking-label);
  --tracking-caps-sm: var(--tracking-label);
  --tracking-caps-xs: var(--tracking-label);
  --tracking-tag: var(--tracking-label);
  --tracking-badge: var(--tracking-label);
  --tracking-badge-lg: var(--tracking-label);

  /* ------------------------------------------------------------- §1 flatness
     No blur, no shadow, no gradient, anywhere — in either renderer. The names
     stay: the ultralight layer and a few call sites still read them, and a
     downstream package that writes \`box-shadow: var(--shadow-tile)\` should get
     nothing rather than an invalid declaration. */
  --blur-panel: 0px;
  --blur-dock: 0px;
  --blur-dim: 0px;

  --shadow-tile: none;
  --shadow-raised: none;
  --shadow-key: none;
  --shadow-thumb: none;
  --shadow-toolbar: none;
  --shadow-dock: none;
  --shadow-panel: none;
  --shadow-cta: none;
  --shadow-switch-on: none;
  --shadow-key-on: none;
  --shadow-card-active: none;
  --shadow-cape: none;

  --inset-raised: none;
  --inset-raised-soft: none;
  --inset-card: none;
  --inset-hud: none;
  --inset-dock: none;
  --inset-field: none;
  --inset-field-panel: none;
  --inset-accent: none;
  --inset-accent-tint: none;
  --inset-switch: none;
  --inset-key: none;
  --inset-kbd: none;
  --inset-canvas: none;
  --inset-row-selected: none;

  /* ---------------------------------------------------------- §5 reactivity
     Monochrome at rest; light and colour appear only where the pointer is.
     Hover in is 140ms ease-out, leave 100ms ease-in, release drains over 200ms,
     and the inspector's columns wipe on a 40ms stagger (§7). */
  --duration-hover-in: 140ms;
  --duration-hover-out: 100ms;
  --duration-drain: 200ms;
  --duration-stagger: 40ms;
}

/* A mod's root sets its category hue; every accent-consuming rule below reads
   \`var(--hue, var(--accent))\` and follows. */
.v-hue--hud { --hue: var(--hue-hud); }
.v-hue--pvp { --hue: var(--hue-pvp); }
.v-hue--visual { --hue: var(--hue-visual); }
.v-hue--utility { --hue: var(--hue-utility); }
`;

/**
 * Layer 1b — the backdrop tokens, emitted here rather than in `design/` because nobody
 * edits `design/` (CONTRACTS.md).
 *
 * A component cannot write `backdrop-filter: blur(var(--blur-panel))` and rely on a
 * layer below zeroing the radius, because `blur(0px)` is still a filter function: the
 * element stays a backdrop root, WebKit re-samples everything behind it, and it can no
 * longer scope invalidation to the part that changed. Measured in game, that made a
 * single mod toggle repaint the whole 2771x1532 panel — and sometimes the whole surface —
 * holding the menu to 13-26 repaints/s where the same view sustains 74/s on small damage.
 *
 * So the *whole property value* is the token, and under the quiet cell system it is
 * `none` in **every** renderer: the system is flat, so nothing blurs anywhere and there
 * is no radius left to express. `none` is also the only value that removes the backdrop
 * root, so the launcher gets the invalidation win the overlay needed.
 */
const DERIVED_LAYER = `

/* ---- Layer 1b: the backdrop tokens (see scripts/build-tokens.mjs) ---- */

:root {
  --backdrop-panel: none;
  --backdrop-dock: none;
  --backdrop-dim: none;
}
`;

/**
 * Layer 2 — what is still renderer-specific once the system is flat.
 *
 * The quiet cell system removed most of what this layer used to carry. Blur, shadow and
 * gradient are gone from *both* renderers now (layer 1a), so the fallbacks that existed
 * to strip them for Ultralight have nothing left to strip; each one is a `none` at
 * `:root` instead of a `none` here. What remains are the two things that are genuinely
 * about the renderer and not about the design:
 *
 *   §2  mix-blend-mode is unsupported, so the grain layer cannot paint and the base
 *       hexes carry a ~1% lift in its place;
 *   §7  dash phase on a rounded corner is inconsistent, so the selection border is solid.
 *
 * Every entry still traces to a row in design/ultralight-notes.md.
 */
const ULTRALIGHT_LAYER = `

/* ==========================================================================
   Layer 2 — [data-renderer="ultralight"]
   The in-game overlay: Ultralight 1.4, a WebKit-derived renderer that is not
   Chromium. Each override below is prescribed by design/ultralight-notes.md.
   ========================================================================== */

[data-renderer='ultralight'] {
  /* §2 mix-blend-mode [hard] — fallback 1, "bake it": skip the runtime noise entirely
     and nudge the base colours ~1% lighter so surfaces do not read as flat black. The
     ramp is the quiet cell system's (layer 1a), lifted rather than replaced. */
  --card-bg: #1A1B1D; /* the system's #191A1C */
  --surface-raised: #232426; /* the system's #212225 */
  --surface-1: var(--card-bg);
  --surface-2: var(--surface-raised);
  --surface-3: var(--surface-raised);
  --raised-bg: var(--surface-raised);
  --key-bg: var(--surface-raised);

  --noise-opacity-frame: 0;
  --noise-opacity-canvas: 0;
  --noise-opacity-card: 0;
  --noise-opacity-raised: 0;
  --noise-opacity-accent: 0;
  --noise-opacity-tint: 0;
  --noise-opacity-chrome: 0;

  /* §1 backdrop-filter [hard] — restated, not because layer 1a leaves anything to fix
     but because this is the layer the overlay is read against. Never branch on
     @supports (backdrop-filter: …): Ultralight may claim support and still no-op, and
     blur(0px) is still a filter function — the element stays a backdrop root and WebKit
     re-samples everything behind it. Measured in game, that made one mod toggle repaint
     the whole 2771x1532 panel and held the menu to 13-26 repaints/s where the same view
     sustains 74/s on small damage. \`none\` is the only value that removes the root. */
  --blur-panel: 0px;
  --blur-dock: 0px;
  --blur-dim: 0px;
  --backdrop-panel: none;
  --backdrop-dock: none;
  --backdrop-dim: none;

  /* The one dim that is still doing a blur's job: the authored blur(3px) behind the
     quick palette becomes one flat layer, a little heavier than the launcher's. */
  --dim-palette: rgba(11, 11, 12, 0.62);

  /* §7 border-style: dashed on a rounded box [risky] — dash phase on rounded corners is
     inconsistent, so the HUD-editor selection falls back to a solid edge. The
     --accent-tint-faint fill already distinguishes the selection. */
  --selection-border-style: solid;
}

/* §1 host contract: the host sets data-glblur="on" while its GL blur pass is running.
   Under the flat system the panel is opaque, so there is nothing behind it to show
   through and its colour does not change — the selector is kept so the host's
   attribute contract (setGlBlur) still has a target. */
[data-renderer='ultralight'][data-glblur='on'] {
  --panel-bg: var(--card-bg);
}

/* ==========================================================================
   Layer 3 — [data-renderer="webview"]
   The launcher: Electron/Chromium (and the Tauri system webview), which has none of
   the limits above. The values in layers 1 and 1a already are the shipped version, so
   this layer only restates the one token layer 2 introduces.
   ========================================================================== */

[data-renderer='webview'] {
  --selection-border-style: dashed;
}

/* Default when <html> carries no data-renderer: behave as the launcher. */
:root {
  --selection-border-style: dashed;
}
`;

/**
 * Layer 2b — the shadow values the host draws in GL, beneath the view.
 *
 * `packages/ingame/src/effects/surfaces.ts` reads a `--shadow-<name>-gl` token per tracked
 * surface and hands it to the host's GL pass, so the overlay could keep an ambient shadow
 * without paying for a blur in Ultralight's CPU rasteriser.
 *
 * Under the quiet cell system there is no shadow to draw. Fill steps carry state and §1
 * allows no shadow anywhere, in either renderer — so these resolve to `none`, which
 * `parseShadow` already reads as "no surface", and the host draws nothing.
 *
 * The values are still *read* out of the cascade rather than retyped, so if a shadow ever
 * comes back — in `design/tokens.css` or in the quiet cell layer — the GL pass follows it
 * with nothing to keep in sync by hand. Last declaration wins, exactly as in CSS.
 */
function glShadowLayer(...cssLayers) {
  const effective = new Map();
  for (const css of cssLayers) {
    for (const [, name, value] of css.matchAll(/^\s*(--shadow-[a-z0-9-]+)\s*:\s*([^;]+);/gim)) {
      effective.set(name, value.trim());
    }
  }
  if (effective.size === 0) return '';
  const lines = [...effective].map(([name, value]) => `  ${name}-gl: ${value};`);
  return `

/* ==========================================================================
   Layer 2b — [data-renderer="ultralight"], shadows for the GL pass
   Read out of the cascade above, for the host to draw beneath the view. The
   quiet cell system is flat, so every one of these is \`none\` and the host
   draws nothing; the layer stays so a shadow that comes back reaches GL.
   ========================================================================== */

[data-renderer='ultralight'] {
${lines.join('\n')}
}
`;
}

writeFileSync(
  path.join(srcDir, 'tokens.css'),
  HEADER +
    '/* ---- Layer 1: pvp/design/tokens.css, verbatim ---- */\n\n' +
    authored +
    QUIET_CELL_LAYER +
    DERIVED_LAYER +
    ULTRALIGHT_LAYER +
    glShadowLayer(authored, QUIET_CELL_LAYER),
  'utf8',
);
process.stdout.write('generated src/tokens.css\n');

/* -------------------------------------------------------------------------- */
/* 2. tokens.json + tokens.ts                                                 */
/* -------------------------------------------------------------------------- */

writeFileSync(path.join(srcDir, 'tokens.json'), authoredJson, 'utf8');
process.stdout.write('generated src/tokens.json\n');

// Every custom property the shipped token sheet declares — the authored :root block plus
// the quiet cell system's own names (--hue-*, --cell-*, the four type tiers) — for
// autocomplete and for the gallery's token inspector.
const names = [authored, QUIET_CELL_LAYER]
  .flatMap((css) => [...css.matchAll(/^\s*(--[a-z0-9-]+)\s*:/gim)])
  .map((m) => m[1]);
const unique = [...new Set(names)].sort();
writeFileSync(
  path.join(srcDir, 'tokens.ts'),
  `/**
 * GENERATED by scripts/build-tokens.mjs — do not edit.
 *
 * The names of every design token declared in \`tokens.css\`. Values live in CSS, not
 * here: this package ships no runtime CSS-in-JS, so JavaScript only ever needs the
 * name (to read one with \`getComputedStyle\`, or to list them in the gallery).
 */

/** Every design-token custom property name, alphabetically. */
export const TOKEN_NAMES = ${JSON.stringify(unique, null, 2)} as const;

/** One design-token custom property name. */
export type TokenName = (typeof TOKEN_NAMES)[number];

/** The two renderer modes \`data-renderer\` selects between. */
export const RENDERERS = ['ultralight', 'webview'] as const;

/**
 * Which renderer the page is running in.
 *
 * - \`ultralight\` — the in-game overlay, inside the JVM. No backdrop-filter, no
 *   mix-blend-mode, no text-shadow, no 3D transforms, no WebGL, no video.
 * - \`webview\` — the launcher, in Chromium or the system webview. Everything works.
 */
export type Renderer = (typeof RENDERERS)[number];
`,
  'utf8',
);
process.stdout.write('generated src/tokens.ts\n');

/* -------------------------------------------------------------------------- */
/* 3. noise.css — the launcher-only grain layer                               */
/* -------------------------------------------------------------------------- */

/** Minimal PNG encoder: greyscale 8-bit, no filtering. */
function encodePng(width, height, pixels) {
  const crcTable = Array.from({ length: 256 }, (_, n) => {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    return c >>> 0;
  });
  const crc32 = (buffer) => {
    let c = 0xffffffff;
    for (const byte of buffer) c = crcTable[(c ^ byte) & 0xff] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const chunk = (type, data) => {
    const length = Buffer.alloc(4);
    length.writeUInt32BE(data.length);
    const body = Buffer.concat([Buffer.from(type, 'latin1'), data]);
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(crc32(body));
    return Buffer.concat([length, body, crc]);
  };
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 0; // greyscale
  const raw = Buffer.alloc((width + 1) * height);
  for (let y = 0; y < height; y += 1) {
    raw[y * (width + 1)] = 0; // filter: none
    for (let x = 0; x < width; x += 1) raw[y * (width + 1) + 1 + x] = pixels[y * width + x];
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

// A fixed-seed 64×64 grain tile. Deterministic so the committed CSS never churns.
const SIZE = 64;
let seed = 0x9f8bff;
const rand = () => {
  seed = (seed * 1664525 + 1013904223) >>> 0;
  return seed / 4294967296;
};
const pixels = new Uint8Array(SIZE * SIZE);
for (let i = 0; i < pixels.length; i += 1) {
  // Centred on mid-grey: `overlay` leaves mid-grey untouched, so the tile only ever
  // nudges a surface a little lighter or a little darker.
  pixels[i] = Math.max(0, Math.min(255, Math.round(128 + (rand() - 0.5) * 90)));
}
const noiseDataUri = `data:image/png;base64,${encodePng(SIZE, SIZE, pixels).toString('base64')}`;

writeFileSync(
  path.join(srcDir, 'noise.css'),
  `/* GENERATED by scripts/build-tokens.mjs — do not edit.

   The grain the design puts over every surface, as a 64px tile scaled to the authored
   --noise-tile size. Painted **only** under [data-renderer="webview"]: Ultralight does
   not implement separable blend modes on composited layers, and the noise would paint
   as an opaque grey wash or be skipped — both worse than no noise
   (design/ultralight-notes.md §2). The ultralight layer bakes a ~1% lift into the base
   hexes instead. */

:root {
  --noise-image: url('${noiseDataUri}');
}

[data-renderer='webview'] .v-noise::after,
:root:not([data-renderer]) .v-noise::after {
  content: '';
  position: absolute;
  inset: 0;
  border-radius: inherit;
  pointer-events: none;
  background-image: var(--noise-image);
  background-size: var(--noise-tile) var(--noise-tile);
  mix-blend-mode: overlay;
  opacity: var(--v-noise-opacity, var(--noise-opacity-card));
}
`,
  'utf8',
);
process.stdout.write('generated src/noise.css\n');
