#!/usr/bin/env node
/**
 * Build `src/tokens.css`, `src/tokens.json`, `src/tokens.ts` and `src/noise.css`.
 *
 * `pvp/design/` is reference material, read-only for everyone, and nothing imports from
 * it at build time (CONTRACTS.md). So the authored `:root` block is **copied** here
 * verbatim — values are never re-typed and never forked — and everything this package
 * adds goes into clearly separated layers below it:
 *
 *   1. the authored `:root` block, byte-for-byte from `design/tokens.css`;
 *   2. `[data-renderer="ultralight"]` — the fallbacks `design/ultralight-notes.md`
 *      prescribes, and nothing else;
 *   3. `[data-renderer="webview"]` — a no-op marker; the authored values already are
 *      the rich version, so this layer exists only so the attribute is meaningful in
 *      both directions.
 *
 * Run automatically by `pnpm build` and `pnpm typecheck`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { deflateSync } from 'node:zlib';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const designDir = path.resolve(pkgRoot, '../../design');
const srcDir = path.resolve(pkgRoot, 'src');

mkdirSync(srcDir, { recursive: true });

const authored = readFileSync(path.join(designDir, 'tokens.css'), 'utf8');
const authoredJson = readFileSync(path.join(designDir, 'tokens.json'), 'utf8');

/* -------------------------------------------------------------------------- */
/* 1. tokens.css                                                              */
/* -------------------------------------------------------------------------- */

const HEADER = `/* ==========================================================================
   @void/ui — design tokens
   GENERATED by scripts/build-tokens.mjs. Do not edit; edit the generator.

   Layer 1 below is pvp/design/tokens.css, copied verbatim. Layers 2 and 3 are the
   renderer modes: put data-renderer="ultralight" on <html> for the in-game bundle
   and data-renderer="webview" for the launcher. Unset behaves as "webview".

   The in-game renderer is the constraint, not the launcher (CONTRACTS.md), so no
   token below depends on backdrop-filter, mix-blend-mode, text-shadow or a 3D
   transform in a way that breaks when those are dropped: the blur radii are read
   through var(--blur-*), which the ultralight layer sets to 0, and the noise layer
   is only painted under [data-renderer="webview"].
   ========================================================================== */

`;

/**
 * Layer 2. Every entry traces to a row in design/ultralight-notes.md; the comment
 * names the section it comes from.
 */
const ULTRALIGHT_LAYER = `

/* ==========================================================================
   Layer 2 — [data-renderer="ultralight"]
   The in-game overlay: Ultralight 1.4, a WebKit-derived renderer that is not
   Chromium. Each override below is prescribed by design/ultralight-notes.md.
   ========================================================================== */

[data-renderer='ultralight'] {
  /* §1 backdrop-filter [hard] — the overlay never asks the renderer to blur what is
     behind it. The game blur is a GL pass in the host, composited underneath, so the
     web layer paints a semi-opaque solid instead. 0.97 is the no-GL-blur value; the
     host raises it to the 0.94 variant by setting data-glblur="on" (see below). */
  --panel-bg: rgba(10, 11, 12, 0.97);
  --palette-bg: rgba(10, 11, 12, 0.96);
  --dim-palette: rgba(10, 11, 12, 0.62); /* the authored blur(3px) becomes one flat layer */

  /* Never branch on @supports (backdrop-filter: …) — Ultralight may claim support and
     still no-op. Reading the radius through a token means the property resolves to
     blur(0px) here and is inert even if it is honoured. */
  --blur-panel: 0px;
  --blur-dock: 0px;
  --blur-dim: 0px;

  /* §2 mix-blend-mode [hard] — fallback 1, "bake it": skip the runtime noise entirely
     and nudge the base colours ~1% lighter so surfaces do not read as flat black. */
  --surface-1: #1a1d21; /* authored #191c20 */
  --surface-2: #23272c; /* authored #22262b */
  --card-bg: rgba(26, 29, 33, 0.94); /* surface-1 @94%, re-derived from the baked hex */
  --raised-bg: rgba(35, 39, 44, 0.97); /* surface-2 @97% */
  --key-bg: rgba(35, 39, 44, 0.96); /* surface-2 @96% */

  --noise-opacity-frame: 0;
  --noise-opacity-canvas: 0;
  --noise-opacity-card: 0;
  --noise-opacity-raised: 0;
  --noise-opacity-accent: 0;
  --noise-opacity-tint: 0;
  --noise-opacity-chrome: 0;

  /* §7 border-style: dashed on a rounded box [risky] — dash phase on rounded corners is
     inconsistent, so the HUD-editor selection falls back to a solid edge. The
     --accent-tint-faint fill already distinguishes the selection. */
  --selection-border-style: solid;
}

/* §1 host contract: when the GL blur pass is running the host sets data-glblur="on"
   and the panel may sit at the lighter alpha. */
[data-renderer='ultralight'][data-glblur='on'] {
  --panel-bg: rgba(10, 11, 12, 0.94);
}

/* ==========================================================================
   Layer 3 — [data-renderer="webview"]
   The launcher: Electron/Chromium (and the Tauri system webview), which has none of
   the limits above. The authored values in layer 1 already are the rich version, so
   this layer only restates the two tokens layer 2 introduces.
   ========================================================================== */

[data-renderer='webview'] {
  --selection-border-style: dashed;
}

/* Default when <html> carries no data-renderer: behave as the launcher. */
:root {
  --selection-border-style: dashed;
}
`;

writeFileSync(
  path.join(srcDir, 'tokens.css'),
  HEADER +
    '/* ---- Layer 1: pvp/design/tokens.css, verbatim ---- */\n\n' +
    authored +
    ULTRALIGHT_LAYER,
  'utf8',
);
process.stdout.write('generated src/tokens.css\n');

/* -------------------------------------------------------------------------- */
/* 2. tokens.json + tokens.ts                                                 */
/* -------------------------------------------------------------------------- */

writeFileSync(path.join(srcDir, 'tokens.json'), authoredJson, 'utf8');
process.stdout.write('generated src/tokens.json\n');

// Every custom property declared in the authored :root block, for autocomplete and for
// the gallery's token inspector.
const names = [...authored.matchAll(/^\s*(--[a-z0-9-]+)\s*:/gim)].map((m) => m[1]);
const unique = [...new Set(names)].sort();
writeFileSync(
  path.join(srcDir, 'tokens.ts'),
  `/**
 * GENERATED by scripts/build-tokens.mjs — do not edit.
 *
 * The names of every design token declared in \`tokens.css\`. Values live in CSS, not
 * here: this package ships no runtime CSS-in-JS, so JavaScript only ever needs the
 * name (to read one with \`getComputedStyle\`, or to list them in the gallery).
 */

/** Every design-token custom property name, alphabetically. */
export const TOKEN_NAMES = ${JSON.stringify(unique, null, 2)} as const;

/** One design-token custom property name. */
export type TokenName = (typeof TOKEN_NAMES)[number];

/** The two renderer modes \`data-renderer\` selects between. */
export const RENDERERS = ['ultralight', 'webview'] as const;

/**
 * Which renderer the page is running in.
 *
 * - \`ultralight\` — the in-game overlay, inside the JVM. No backdrop-filter, no
 *   mix-blend-mode, no text-shadow, no 3D transforms, no WebGL, no video.
 * - \`webview\` — the launcher, in Chromium or the system webview. Everything works.
 */
export type Renderer = (typeof RENDERERS)[number];
`,
  'utf8',
);
process.stdout.write('generated src/tokens.ts\n');

/* -------------------------------------------------------------------------- */
/* 3. noise.css — the launcher-only grain layer                               */
/* -------------------------------------------------------------------------- */

/** Minimal PNG encoder: greyscale 8-bit, no filtering. */
function encodePng(width, height, pixels) {
  const crcTable = Array.from({ length: 256 }, (_, n) => {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    return c >>> 0;
  });
  const crc32 = (buffer) => {
    let c = 0xffffffff;
    for (const byte of buffer) c = crcTable[(c ^ byte) & 0xff] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const chunk = (type, data) => {
    const length = Buffer.alloc(4);
    length.writeUInt32BE(data.length);
    const body = Buffer.concat([Buffer.from(type, 'latin1'), data]);
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(crc32(body));
    return Buffer.concat([length, body, crc]);
  };
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 0; // greyscale
  const raw = Buffer.alloc((width + 1) * height);
  for (let y = 0; y < height; y += 1) {
    raw[y * (width + 1)] = 0; // filter: none
    for (let x = 0; x < width; x += 1) raw[y * (width + 1) + 1 + x] = pixels[y * width + x];
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

// A fixed-seed 64×64 grain tile. Deterministic so the committed CSS never churns.
const SIZE = 64;
let seed = 0x9f8bff;
const rand = () => {
  seed = (seed * 1664525 + 1013904223) >>> 0;
  return seed / 4294967296;
};
const pixels = new Uint8Array(SIZE * SIZE);
for (let i = 0; i < pixels.length; i += 1) {
  // Centred on mid-grey: `overlay` leaves mid-grey untouched, so the tile only ever
  // nudges a surface a little lighter or a little darker.
  pixels[i] = Math.max(0, Math.min(255, Math.round(128 + (rand() - 0.5) * 90)));
}
const noiseDataUri = `data:image/png;base64,${encodePng(SIZE, SIZE, pixels).toString('base64')}`;

writeFileSync(
  path.join(srcDir, 'noise.css'),
  `/* GENERATED by scripts/build-tokens.mjs — do not edit.

   The grain the design puts over every surface, as a 64px tile scaled to the authored
   --noise-tile size. Painted **only** under [data-renderer="webview"]: Ultralight does
   not implement separable blend modes on composited layers, and the noise would paint
   as an opaque grey wash or be skipped — both worse than no noise
   (design/ultralight-notes.md §2). The ultralight layer bakes a ~1% lift into the base
   hexes instead. */

:root {
  --noise-image: url('${noiseDataUri}');
}

[data-renderer='webview'] .v-noise::after,
:root:not([data-renderer]) .v-noise::after {
  content: '';
  position: absolute;
  inset: 0;
  border-radius: inherit;
  pointer-events: none;
  background-image: var(--noise-image);
  background-size: var(--noise-tile) var(--noise-tile);
  mix-blend-mode: overlay;
  opacity: var(--v-noise-opacity, var(--noise-opacity-card));
}
`,
  'utf8',
);
process.stdout.write('generated src/noise.css\n');
