# ---------------------------------------------------------------------------
# void-client — Legacy Fabric mod for Minecraft 1.8.9
# ---------------------------------------------------------------------------
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Fabric / Legacy Fabric
minecraft_version   = 1.8.9
yarn_mappings       = 1.8.9+build.604
loader_version      = 0.16.14

# Mod
mod_version         = 0.1.0
maven_group         = dev.void
archives_base_name  = void-client
