package dev.voidmc.lod.source;

import dev.voidmc.expanse.world.terrain.Column;
import dev.voidmc.expanse.world.terrain.EarthChunkGenerator;
import dev.voidmc.expanse.world.terrain.Landform;
import dev.voidmc.expanse.world.terrain.TerrainModel;
import dev.voidmc.lod.core.ColumnSample;
import net.minecraft.core.Holder;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.biome.Biome;

/**
 * The fast path for Expanse's Earth worlds: the terrain model answers a column (ground height, rivers,
 * crater lakes, landform, climate) in a couple of microseconds, against the tens a generic noise walk
 * costs, so the whole horizon can be built before a player has finished looking at it.
 *
 * <p>Everything the model knows shows up at a distance: rivers are cut to their own water level and
 * carry it across the plate, crater lakes and lava fill volcano tops, canyon walls are banded like
 * terracotta, salt flats are white, and the snow line follows the model's own temperature lapse, so a
 * mountain range is white at the top for the same reason in the LOD as in the chunks.
 *
 * <p>Only loaded when Expanse is: nothing else references this class.
 */
public final class ExpanseSource extends WorldgenSource {
	private static final int[] CANYON_BANDS = {0xA4582C, 0x8C3F2C, 0xC9A88E, 0x9C6234, 0xB2704A, 0x7E4A36};
	private static final int SALT = 0xE8E4DA;
	private static final int BASALT = 0x4C4B50;
	private static final int LAVA = 0xE0641A;
	private static final int ROCK = 0x8A8580;

	private final TerrainModel model;

	private ExpanseSource(ServerLevel level, TerrainModel model, long version) {
		super(level, version);
		this.model = model;
	}

	/** The Earth source for a level, or null if the level is not generated by Expanse's Earth terrain. */
	public static WorldgenSource tryCreate(ServerLevel level, long version) {
		if (level.getChunkSource().getGenerator() instanceof EarthChunkGenerator earth) {
			return new ExpanseSource(level, earth.model(level.getChunkSource().randomState()), version);
		}
		return null;
	}

	@Override
	public void sample(int x, int z, int cell, ColumnSample out) {
		// Read everything from the column before anything else samples the model: its column is reused.
		Column c = this.model.sample(x, z);
		int ground = (int) Math.ceil(c.height);
		int water = Integer.MIN_VALUE;
		boolean lava = false;
		if (c.inChannel()) {
			water = c.waterTop();
			ground = Math.min(ground, c.bed());
		} else if (c.fjord || ground < this.seaLevel) {
			water = this.seaLevel;
		}
		if (c.crater > ground) {
			water = Math.max(water, (int) Math.ceil(c.crater));
			lava = c.craterLava;
		}
		int landform = c.landform;
		float temperature = c.temperature;
		float coast = c.coast;
		float uplift = c.uplift;

		Holder<Biome> biome = this.biome(x, Math.max(ground, this.seaLevel), z);
		BiomeLooks.Look look = this.looks.get(biome);
		out.ground = ground;
		out.water = water;
		out.waterColor = lava ? LAVA : look.waterColor();
		int color = switch (landform) {
			case Landform.CANYON -> CANYON_BANDS[Math.floorMod(ground / 5, CANYON_BANDS.length)];
			case Landform.SALT_FLAT -> SALT;
			case Landform.VOLCANIC -> BASALT;
			default -> look.groundColor();
		};
		boolean wet = water != Integer.MIN_VALUE && water > ground;
		if (!wet && landform == Landform.NONE) {
			if (temperature < 0.15F) {
				color = BiomeLooks.snow();
			} else if (ground <= this.seaLevel + 2 && coast < 48 && look.ground() == BiomeLooks.Ground.GRASS) {
				color = BiomeLooks.sand();
			} else if (uplift > 1.1F && ground > 150) {
				// high, young ranges are bare above the tree line
				color = ROCK;
			}
		}
		out.groundColor = color;
		if (!wet && landform != Landform.SALT_FLAT && landform != Landform.VOLCANIC && !(uplift > 1.1F && ground > 150)) {
			out.canopy = look.canopy();
			out.cover = look.cover();
			out.canopyColor = temperature < 0.15F ? dev.voidmc.lod.source.BiomeLooks.scale(look.canopyColor(), 1.25F) : look.canopyColor();
		}
	}
}
